### ISSUE TITLE
frmMain: qgis.core and qgis.core not found

### ISSUE THREAD

**Issue by Techre** [USEPA/SWMM-EPANET_User_Interface#10]
```
        **from qgis.core import QgsApplication
        from qgis.gui import QgsMapCanvas**
```

give unresolved imports.

The error message becomes:
**QGIS libraries not found, Not creating map
DLL load failed: The specified procedure could not be found.**

I did install QGis in C:\OSGeo4W64 . I tried 3 different versions (2.16, 2.14 and 2.12)

I run Windows and these are my user variables;

```
 OSGEO4W_ROOT: _C:\OSGeo4W64\_

 PATH : _C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\;C:\Program Files (x86)\Skype\Phone\;C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Users\DEVOGELR\Documents\casadi\casadi-py34-np1.9.1-v3.0.1-64bit\casadi;C:\SQLite3;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Enterprise Vault\EVClient\x64;C:\OSGeo4W64\bin;C:\OSGeo4W64\apps\qgis\bin;C:\OSGeo4W64\apps\qgis\bin_
```

 PYTHONHOME: _C:\Anaconda2_

 PYTHONPATH: _C:\Anaconda2_

QGIS: _C:\OSGeo4W64\apps\qgis_

QGIS_PREFIX_PATH: _C:\OSGeo4W64\apps\qgis_

See attached file for my eclipse PYTHONPATH
![eclipse](https://cloud.githubusercontent.com/assets/20206032/18875759/680d4f84-84c7-11e6-84c8-838dc4068ad8.png)

**Comment by MarkGrayRESPEC** [comment]
I see that your PATH includes an Anaconda version of Python before the OSGeo version. For this to work, it needs to only find the OSGeo Python. On my development machine for this project I have removed all other versions of Python to reduce confusion. It may be possible to keep another version, but you will have to make sure only the OSGeo version is in the PATH, PYTHONHOME, and PYTHONPATH variables. You may want to take a look at our freshly updated "Getting Started" instructions at: https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Getting-Started-as-a-Developer
Please follow up to let us know whether you got it working and whether you have any tips on using Eclipse with this project.

**Comment by Techre** [comment]
Hi Marc,

Thanks for the reply. Because I need Python on my machine I installed everything according to your guide on another computer, including pyCharm. When installing Qgis I had to install Tkinter as well, otherwise the code would not run.

I have the same problem.

```
C:\OSGeo4W64\bin\python.exe C:/Users/_/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py
Try loading ENOutputAPI-64.dll from C:\Users\_\PycharmProjects\SWMM-EPANET_User_Interface\src\Externals\epanet\outputapi
Loaded ENOutputAPI-64.dll: <CDLL 'C:\Users\_\PycharmProjects\SWMM-EPANET_User_Interface\src\Externals\epanet\outputapi\ENOutputAPI-64', handle 6bfc0000 at aa56588>
QGIS libraries not found, Not creating map
```

**Comment by tudorbarascu** [comment]
Hi,
@MarkGrayRESPEC First of all thanks for working on this project.. can't wait on trying your Epanet/QGIS work. Thanks also for choosing QGIS/QT.

@Techre As on Windows, the OSgeo4W64 installer has its own version of PYTHON, it's clear that QGIS must load some env variables before starting. By looking how QGIS is starting (env. variables) you can see how you can solve your issue.

Basically, check what happens in ``bin\o4w_env.bat`` or in ``qgis.bat`` files and you'll  figure out the solution.

For more details, take a look at https://blog.qtibia.ro/2016/06/09/how-to-setup-pycharm-for-qgis-development-under-linux-and-windows/ and see the Windows part.

You can easily keep multiple versions of Python on your machine without having problems between them. As a rule, don't make a PYTHONPATH env variable system wide, but load it with a script (.bat file) before you start your custom Python aware program. If in doubt, always do a import sys + print sys.path to see which directories are traversed by your Python executable and in which order.

Hope it helps,
Tudor

**Comment by Techre** [comment]
Hi tudorbarascu,

Thank you for your quick reply. I think PyCharm does find the libraries now as the error is risen by "C:\OSGeo4W64\apps\qgis\python\qgis\PyQT\QtCore.py"

But I will try you solution tonight.
