### ISSUE TITLE
EPANET_MTP4-r2_Can users redefine plot ranges?

### ISSUE THREAD

**Issue by ucchejbb** [USEPA/SWMM-EPANET_User_Interface#100]
When attempting to plot the results from a simulation, the color scheme for pressure was dominated by one large negative value. The interface automatically scaled all the results evenly between this large negative value, and the remainder of the simulated pressures. This resulted in all the nodes being displayed as a single color. Similarly, this automatic scaling will result in even distribution of the range, even if a user would like colored ranges to be 0-24hr, 24-48, ... 168hr+ or something similar for age, or <0.2mg/L, 0.2-0.5, >1.mg/L for chlorine.

How can a user select custom plot ranges, or color ranges?

**Comment by PaulDudaRESPEC** [comment]
On a plot the toolbar contains a button to edit axis parameters.  Within the map a user may right-click on the legend in the 'layers' tab and edit the colors and ranges.
