### ISSUE TITLE
EPANET_File --> Preferences not yet implemented

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#104]
The EPANET2 has the functions of File-Preferences Menu which is useful for the user to set up temporary directory, automatic backup options, and decimal points control in Precision Display Options. Currently, the UI has no functions for it, thus simulation results are represented only by two decimal points.

**Comment by PaulDudaRESPEC** [comment]
Implemented preferences form for available options and numerical precision.
