### ISSUE TITLE
EPANET_[MTP4-r2]_[Canvas Map]_[Junction property view disappears]_[high]

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#105]
The Canvas shows the network map to the user. The user can view the properties of each junction or pipe double-clicking the object with the select object mode. After the simulation with a network, Junction property viewer disappears.

**Comment by PaulDudaRESPEC** [comment]
cannot reproduce this in dev-ui-py3qt5 version
