### ISSUE TITLE
EPANET_[MTP4-r2]_[Canvas Map]_[No information view on map]_[high]

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#106]
After File-Open a network file, the Map in Project Explorer has the default property of 'None' of the Nodes. When the user tried to change to different components, the map does not update at all. For examples, 'Elevation', 'Base Demand', 'Initial Quality'.

**Comment by PaulDudaRESPEC** [comment]
Functionality restored.
