### ISSUE TITLE
EPANET_[MTP4-r2]_[Toolbar]_[Select vertex icon toggle]_[low]

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#107]
Object Selection icon in the toolbar is made as a toggle switch. When the user clicks another icon, the automatic change of toggle switch is needed.

**Comment by rjanke20** [comment]
Different icons display different behaviors.  Not clear to user how selection icon (or other icons) work.

**Comment by woohn** [comment]
Corrected to 'vertex selection' icon. When the user wants to select vertex during the drawing mode (e.g. adding a node or junction), the vertex icon does not work. Even though it is selected.

**Comment by PaulDudaRESPEC** [comment]
fixed along with #168
