### ISSUE TITLE
Any release notes for MTP 3?

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#11]
Hi,

Any release notes planned for MTP3 like the those for [MTP 2](https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/MTP-2)?

Thanks!

**Comment by dickinsonre** [comment]
Thanks for making this interface!  it looks great.  However, I seem to be only able to import nodes in the MTP 3 version of SWMM5 along with time series.

**Comment by michaeltryby** [comment]
@dickinsonre Thanks for your interest in our project. 

As you know, the UIs are under active development. MTP 3 combines functionality from MTPs 1 and 2 with map rendering. We are working on issues with the install package related to map rendering not working for some users. 

Can you please be more specific about the issue you are having?

**Comment by dickinsonre** [comment]
Thanks for the reply.  The problem (or just a feature not implemented) is the following:
1, I open a SWMM 5 file
2. The SWMM5-UI imports the file
3. I only see the nodes and not the links in the project tab
4.  I can click on the node ID and see the right data in the property editor

**Comment by PaulHummelRESPEC** [comment]
Here are release notes for MTP 3:
https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/MTP-3-Release-Notes

**Comment by MarkGrayRESPEC** [comment]
Closing this issue now that MTP 3 release notes are available. @dickinsonre Please create a new issue with a title something like "SWMM MTP 3 does not display links for this input file"
Attach an example input file that demonstrates your problem by dragging the file into the comment before you submit it.

**Comment by eladsal** [comment]
Thank you!
