### ISSUE TITLE
EPANET_MTP4-r2 error 422

### ISSUE THREAD

**Issue by dly9000** [USEPA/SWMM-EPANET_User_Interface#110]
I have an inp file that runs just fine on my normal epanet installation and dll bbut am receiving this error when I run it in the new user interface 

Error opening model output: path/inpfile_trial_08_10_23.out
SWMM output error calling ENR_newOutValueSeries:
EPANET output error #422

Behind the error it says run successful though

**Comment by PaulDudaRESPEC** [comment]
see also issue #228

**Comment by TongZhai** [comment]
@dly9000 We are always interested in testing the model engines/output APIs with real world user provided model input files, if you are interested in helping us in this respect, please send us your input file that the EPANET (or SWMM) failed on. You can email it to individual developers if you don't want to post it here and we will ensure they will only be used for software testing.

**Comment by dickinsonre** [comment]
@TongZhai how do we email these sample models to you?

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
