### ISSUE TITLE
Creating install packages for Windows doesn't proceed correctly

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#114]
Dear Community,

Hello,
I am trying to create the install package for EPANET and SWMM and it seems something doesn't go correctly. I have followed the instruction given at Wiki and except warnings that appear about not finding the libraries libzmq, qgis-gui, and api-ms-win-crt-*, the rest seems compiling correctly. 

74625 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\message.pyd
74663 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\_device.pyd
74703 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\utils.pyd
74746 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\socket.pyd
74787 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\_poll.pyd
74829 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\context.pyd
74875 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\error.pyd
74921 WARNING: lib not found: libzmq.pyd dependency of C:\OSGeo4W64\apps\Python27\lib\site-packages\zmq\backend\cython\_version.pyd
75757 WARNING: lib not found: qgis_gui.dll dependency of C:\OSGeo4W64\apps\qgis\python\qgis\_gui.pyd
75809 WARNING: lib not found: qgis_core.dll dependency of C:\OSGeo4W64\apps\qgis\python\qgis\_gui.pyd
75912 WARNING: lib not found: qgis_core.dll dependency of C:\OSGeo4W64\apps\qgis\python\qgis\_core.pyd
76758 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
76806 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
76840 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
76878 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
76923 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
76977 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
77013 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\osgeo4~1\bin\libtiff.dll
77616 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\osgeo4~1\bin\sqlite3.dll
77650 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\osgeo4~1\bin\sqlite3.dll
77684 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\osgeo4~1\bin\sqlite3.dll
77717 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\osgeo4~1\bin\sqlite3.dll
77754 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\osgeo4~1\bin\sqlite3.dll
78427 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\osgeo4~1\bin\liblzma.dll
78464 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\osgeo4~1\bin\liblzma.dll
78508 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\WINDOWS\system32\vcruntime140.dll
78541 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\WINDOWS\system32\vcruntime140.dll
78576 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\WINDOWS\system32\vcruntime140.dll
78609 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\WINDOWS\system32\vcruntime140.dll
78646 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\WINDOWS\system32\vcruntime140.dll 

It successfully finish compilation, however when I am trying to run the compiled version of EPANET or SWMM, it fails to execute the script. I am using Windows 10, 64 bit.
There are few additional steps that I guess is dropped from manual. I would appreciate if someone can help me with this. I appreciate.

**Comment by TongZhai** [comment]
[New instruction for creating installation packages for the python 3 and Qt 5 code base](https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Create-Installation-Package-for-Windows-10-(python-3-Qt-5-version) is created.
