### ISSUE TITLE
EPANET project defaults editor fails to display

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#117]
Version: EPANET UI MTP4r2

Description: 
Noticed the following strange behavior with the EPANET project defaults editor:
1) If you open EPANET with a blank project and then immediately hit the new project button, the project defaults editor will not display. 
2) When the defaults editor does display, it is missing an entry for "Pipe" Objects

Priority: Low

**Comment by michaeltryby** [comment]
Description Continued: 
3. Model elements are not being created with default values as expected.

**Comment by ucchejbb** [comment]
I'm also having trouble accessing the "Defaults" (which is just "Default..." at the moment) from a new file. Opening a saved inp file, and I can access this menu. 

Pipes created in a new file have 0.0 diameter and 0.0 length. Adding a pipe to a saved inp model seems to correctly add a pipe with default parameters.

**Comment by PaulDudaRESPEC** [comment]
Model elements are now created with the default values as expected.
