### ISSUE TITLE
EPANET Pointer behavior should reflect interaction mode

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#119]
Version: EPANET MTP4r2

Description: When creating model objects on the map the mouse pointer does not change to reflect the interaction mode. The mouse pointer should change to reflect the current mode (pan, zoom, etc.). 

Priority: Feature request

**Comment by PaulDudaRESPEC** [comment]
Tested all the cursor changes for the various interaction modes, and they all work now.
