### ISSUE TITLE
EPANET Model only runs if there are no spaces in the install path

### ISSUE THREAD

**Issue by MarkGrayRESPEC** [USEPA/SWMM-EPANET_User_Interface#12]
If installed in a location like "C:\Program Files" with a space somewhere in the path, EPANET reports "File Error 305: cannot open hydraulics file."

Workaround: install in a folder where there is no space in the path.

It may be possible to solve this with a change in Python code or it may require recompiling epanet2_amd64.dll which was compiled by Sandia.

**Comment by rjanke20** [comment]
I installed MTP3r1 to c:\EPANET_UI_Testing as well as to just c:\, in both cases the simulation failed with the same message "File Error 305...".

**Comment by MarkGrayRESPEC** [comment]
I have set up a new virtual machine environment for testing installed versions of this software without interference from development environments or other installed software. It is easy to roll back to a "clean" version of the virtual machine so previous testing does not affect the current test.

In my first test of EPANET-UI-MTP3r1 on the virtual machine, I installed in C:\Program Files (x86)\EPANET-UI\
It is not displaying the map. I have entered that as a separate issue.

When I ignore the fact that the map is not displaying and load the first test project Net1.inp, the model runs correctly via Project/Run Simulation or via the "lightning bolt" Run Simulation toolbar button.

Originally I thought the issue was with spaces in the path, but now it is not clear to me what is causing this issue.

I will continue on a path toward understanding the moment when this error can happen and see if I can find a fix even though I have so far not been able to reproduce the error in the test environment. The error message itself seems to be coming from inside the model code.

**Comment by MarkGrayRESPEC** [comment]
"File Error 305: cannot open hydraulics file" occurs when the user does not have write permission to the folder where EPANET-UI is installed. This is a good clue for working toward a solution. A temporary workaround might be installing to a folder in the user's home folder.

**Comment by michaeltryby** [comment]
EPANET tries to open and write to a temporary hydraulics file. We probably should be doing this in the system temporary directory and not where the UI is installed.

**Comment by eladsal** [comment]
Windows has special locations for applications data and files, the AppData folder. At the run command line (Win-R) type %appdata%. Inside the AppData folder you can find the temp directory, try %temp%.

**Comment by MarkGrayRESPEC** [comment]
EPANET-UI-MTP3r2 installer is now uploaded into the MTP 3 release. This version tries to change into the directory containing the input file before running the model. If that does not work, it tries changing to the system temporary directory. This has fixed the issue in testing, so I am closing this issue.
