### ISSUE TITLE
EPANET Vertex editing mode does not work

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#121]
Version: MTP4r2

Description: Vertex editing mode does not work. Unable to select and move vertices. Vertex indicators (i.e. red "x" ) do not redraw correctly when vertex editing mode is turned off/on. 

Priority: Low

**Comment by PaulDudaRESPEC** [comment]
Tested with pipes in epanet and conduits, subcatchments in swmm.  Also redraws correctly when vertex editing mode is turned on/off.
