### ISSUE TITLE
EPANET Undo/Redo not working

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#122]
Version: EPANET MTP4r2

Description: Undo/Redo not working for model element creation, deletion, and move operations.

Priority: Medium

**Comment by ehsanMa86** [comment]
Undo/Redo not working for Labels as well.

**Comment by rjanke20** [comment]
Concur, undo does not seem to remove aberrant links due to "Add pump link" or "Add valve link".
--

**Comment by PaulDudaRESPEC** [comment]
tested undo/redo with model objects (nodes, links, labels, subcatchments) in both SWMM and EPANET, now working as intended.
