### ISSUE TITLE
SWMM_MTP4-r2_Tools Menu --> Program Preferences not yet implemented

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#123]
Both the "Program Preferences..." and "Configure Tools" options do nothing.  In the old UI, "Program Preferences" allowed the user to set general options and numerical precision for results.

**Comment by barrc** [comment]
see #104

**Comment by PaulDudaRESPEC** [comment]
Removed 'configure tools' -- 'plugins' provide the customization functionality in the open source UI

**Comment by PaulDudaRESPEC** [comment]
Implemented preferences form for available options and numerical precision.
