### ISSUE TITLE
SWMM_MTP4-r2_Run new file first time

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#127]
If you build a new model and click run, the UI prompts you to save the model.  After saving, a pop-up says "SWMM input file not found."  If you close and reopen the UI, open the new model, and run it, it will run successfully.

See #93 for similar problem with EPANET UI.

**Comment by barrc** [comment]
Also when creating a new model, if you press "Save" the UI should prompt where to save the file.

**Comment by PaulDudaRESPEC** [comment]
This fix has been tested by creating a new model and clicking run, the user is prompted to save the model as expected.  Also after creating a new model and clicking Save, the user is prompted with the SaveAs dialog.
