### ISSUE TITLE
SWMM-MTP4_-r2_Saving time series plots

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#128]
Saving time series plots as .jpegs has sometimes led to strange images (see x-axis label):

![time_series_plot2](https://user-images.githubusercontent.com/13906772/34580386-aeb6ad3a-f141-11e7-868e-f3bd57092c8e.jpeg)

Saving as a .tiff does not work.  I get this pop-up:

![capture](https://user-images.githubusercontent.com/13906772/34580299-5312cb44-f141-11e7-937a-259dbc1f37d8.PNG)

Similar to #28 for EPANET, saving as a .png causes the program to crash.

**Comment by barrc** [comment]
The 'save' icon on scatter plots does nothing.

**Comment by dickinsonre** [comment]
If i try to save  png file the program crashes.  It may be a function of previous steps by me, however.

**Comment by PaulDudaRESPEC** [comment]
Appears to be fixed by using the python 3 matplotlib
