### ISSUE TITLE
Add confirmation of dangerous operations such as New Project and Exit

### ISSUE THREAD

**Issue by MarkGrayRESPEC** [USEPA/SWMM-EPANET_User_Interface#13]
The undo stack could be consulted to see whether there are pending unsaved changes.

**Comment by MarkGrayRESPEC** [comment]
Added a first draft of this functionality. Currently the checking is limited to undo-able map interactions (adding, removing, moving objects) and does not yet cover just editing properties or options.

**Comment by PaulDudaRESPEC** [comment]
Fixed.  Each UI element that makes changes to the core has been tested to ensure it properly triggers the 'unsaved changes' warning.
