### ISSUE TITLE
SWMM-MTP4-r2-Map labels

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#130]
Anchor node doesn't work.

There are no options for font.

Bold and italics don't work.  If you set bold to True and click OK, then reopen the dialog box, it will still say True but the label will not be bold.  If you set italics to True and click OK, then reopen the dialog box, it will have changed back to False.  

Changing the size doesn't work.  

Changing the coordinates doesn't move the label.  If you save the file, close the UI, and reopen, the label will be in the correct spot.

**Comment by michaeltryby** [comment]
See also, Issue #132

**Comment by barrc** [comment]
Initially when you create a label using the add a map label button on the toolbar, it automatically opens the map labels editor so you can edit the text.  If you have done File -> New in your session, it doesn't bring up the map labels editor and just places a number.  Sometimes you aren't able to edit or delete the new label/number, but sometimes you are.

**Comment by barrc** [comment]
See also issue #197

**Comment by PaulDudaRESPEC** [comment]
Anchor nodes, fonts, font size, bold and italics are now all implemented and tested.
