### ISSUE TITLE
EPANET Cannot delete model object when selected from network map

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#131]
Version: EPANET MTP4r2

Description: When a model object is selected from the map it can not be deleted. It can only be deleted when it is selected from the project browser. The model object should be deleted whether it is selected from the map of the project browser. 

Severity: Low

**Comment by PaulDudaRESPEC** [comment]
Deleting from the map works in the current dev-ui-py3qt5 branch
