### ISSUE TITLE
EPANET Cannot view status report

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#137]
Version: EPANET MTP4r2

Description: After an unsuccessful attempt to run a simulation, the user is prompted to check the status report for the cause of the failure, however, the status report can not be viewed because it is empty or the a web browser is launched instead of the text file viewer.  

Severity: Medium

**Comment by PaulDudaRESPEC** [comment]
For both EPANET and SWMM, the UI attempts to open the status report file using the OS default program associated with the file type.  In this case trying to open a '.txt' file, a basic text editor (notepad) will open, unless your operating system default is set to open a '.txt' file in a web browser.  To me this behavior is desirable, essentially opening the file in whatever program you have set to open .txt files; one user may prefer notepad, another may prefer notepad++ or wordpad.  

I am marking this closed for now to move on to bigger issues, although feel free to comment and reopen if you have a better suggestion of how this feature should work.
