### ISSUE TITLE
SWMM model element creation causes orphaned elements

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#140]
Version: SWMM MTP4r2

Description: There are two ways to create model elements. 1) using the toolbar, and 2) using the project explorer. Using the toolbar the user adds a model element to the map and then double clicks the model element to edit its attributes. Using the project explorer the user selects the category and hits the "+" button and is immediately able to edit attributes, but the element is not added to the map. This results in orphaned model elements that are not represented on the map canvas. 

These two approaches for creating model elements need to be coordinated so that orphaned model elements don't get created. 

Severity: Medium

**Comment by michaeltryby** [comment]
Similar to issue #120 in EPANET, when conduits are created in SWMM and the operation is canceled an orphaned conduit is created that is not drawn on the map.

**Comment by michaeltryby** [comment]
When the orphaned conduit is deleted from the conduits list and no longer appears on the map, it still causes the simulation to fail when the input file gets parsed by the engine. It shows up in the [xsect] section. So conduits are not being deleted properly.

**Comment by PaulDudaRESPEC** [comment]
This fix was tested with sample data, adding subcatchments, rain gages, labels, and conduits both from the project explorer and using the map toolbar.
