### ISSUE TITLE
SWMM_MTP4-r2_Events editor from SWMM 5.1.012+

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#142]
The events editor is missing.  In the old UI, the events editor was under Options.

**Comment by PaulDudaRESPEC** [comment]
I don't see an events editor in the old interface.  I'm probably overlooking it.  @barrc, can you provide more specific info or send an image?  Thanks.

**Comment by dickinsonre** [comment]
Hello @PaulDudaRESPEC the events dialog under options was added recently to SWMM5.  You need to use the SWMM 5.1.012 GUI and Engine.

**Comment by barrc** [comment]
@PaulDudaRESPEC here is a screenshot:

![image](https://user-images.githubusercontent.com/13906772/42951456-0d7e1c12-8b2b-11e8-933f-df5088ac3c27.png)

**Comment by PaulDudaRESPEC** [comment]
Related to issue #192

**Comment by PaulDudaRESPEC** [comment]
Events editor has been implemented and tested
