### ISSUE TITLE
SWMM Connection from subcatchment to outlet not rendered on map

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#143]
Version: SWMM MTP4r2

Description: When creating a subcatchment and editing its outlet property, the link between the subcatchment and outlet (dashed blue line) is not rendered. When the project is saved and reopened, the links between subcatchment and outlets are then being rendered.  

Severity: Low

**Comment by barrc** [comment]
Similarly, if you edit the inlet or outlet node of a conduit in the conduit editor, it is not rendered.  When the project is saved and reopened, it is rendered properly.

**Comment by PaulDudaRESPEC** [comment]
Fixed and tested for subcatchments, nodes, links, and labels for both SWMM and EPANET.
