### ISSUE TITLE
SWMM model element selection is clunky

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#145]
Version: SWMM MTP4r2

Description: Sometimes when attempting a select a model element the user is prompted to "Choose a Type ?" and select the element class desired to complete a selection operation on the map. This makes selecting model elements on the map seem clunky. A better way to select model elements residing in different layers needs to be developed. 

Severity: Low

**Comment by PaulDudaRESPEC** [comment]
Removed the selection dialog, instead using the name selected in the object tree.
