### ISSUE TITLE
SWMM Time series editor view option not working

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#146]
Version: SWMM MTP4r2

Description: Time series editor view option does not produce a plot of the time series

Severity: Low

**Comment by barrc** [comment]
Maybe this is an intermittent problem.  The time series editor view option is working for me.

**Comment by dickinsonre** [comment]
The time series editor view options shows  a graph for me as well.

**Comment by michaeltryby** [comment]
Apparently, there are conditions where it does and doesn't work.

**Comment by PaulDudaRESPEC** [comment]
I have not been able to reproduce this bug.

**Comment by PaulDudaRESPEC** [comment]
Still have not been able to reproduce this bug; it seems to be working fine.  Since we've done a lot since this issue was reported (changing versions of py, qt, etc.), I'm changing this issue from 'bug' to 'needs more info'.

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
