### ISSUE TITLE
SWMM_MTP4-r2_Query doesn't work for all variables

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#149]
1. Find subcatchments with LID doesn't work.  If you search for a LID type you have, it says "0 items found" and highlights the correct subcatchment, but then if you search for a LID type not in the project, it keeps the subcatchment highlighted and selected on the sidebar.
2. Find nodes with inflow highlights objects on the map and the sidebar but still says "0 items found"
3. In the old UI, you can search for objects with a given value at a certain time period.  You do this by selecting a time period to query for from the map browser.  I think that this query is only looking at the first timestep.

**Comment by PaulDudaRESPEC** [comment]
Items 1 and 2 are fixed and tested.  Item 3 is still to be done, so this issue remains open.

**Comment by PaulDudaRESPEC** [comment]
Verified that Issue 3 is now resolved as well.  As in the old UI, the map browser is used to display the time step to query.
