### ISSUE TITLE
SWMM_MTP4-r2_Project Details not yet implemented

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#150]
* Summary does nothing.  
* Details does nothing.  
* Simulation options does nothing.  This wasn't a menu item in the old UI so maybe it can be removed.

**Comment by dickinsonre** [comment]
Options is an important part of the existing SWMM5 DELPHI GUI - is this what you mean by the OLD UI or do you mean an earlier version of this UI?  It seems the Menu Item would be good if it pointed to the right dialog
![2018-01-06_1648](https://user-images.githubusercontent.com/5599939/34644293-b0b1112c-f301-11e7-8322-042bda5496dc.png)

**Comment by barrc** [comment]
I meant that in the Delphi GUI there is no menu item under Project linking to simulation options:

![image](https://user-images.githubusercontent.com/13906772/34684533-3ae8444c-f45a-11e7-979a-5933c88e2571.png)

**Comment by PaulDudaRESPEC** [comment]
'Details' feature is still to be implemented.
