### ISSUE TITLE
SWMM_MTP4-r2_Can't undo adding GIS data

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#152]
After adding a vector layer or a raster layer, edit -> undo doesn't work.

**Comment by TongZhai** [comment]
@barrc The code improvements related to issue #156 and other map related issues allow users to add unlimited number of vectors and rasters into the UI, users can right-mouse click on any layer to choose 'Remove' layer to delete them from the UI. All non-model vector layers will be placed in the 'Others' map group and all raster layers will be placed in the 'Base Maps' group on the Layer tab.
