### ISSUE TITLE
SWMM_MTP4-r2_Opening status report launches web browser

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#158]
Trying to open the status report launches a web browser (Internet Explorer, which is not my default web browser).  The browser does not show the status report and says "This page can't be displayed."  The status report is present in the simulation's folder and can be opened in a text editor.  This occurs both when the simulation completes successfully and when it fails.

**Comment by barrc** [comment]
See #137 for the web browser issue.  I haven't yet encountered a blank status report for SWMM.

**Comment by PaulDudaRESPEC** [comment]
For both EPANET and SWMM, the UI attempts to open the status report file using the OS default program associated with the file type.  In this case trying to open a '.txt' file, a basic text editor (notepad) will open, unless your operating system default is set to open a '.txt' file in a web browser.  To me this behavior is desirable, essentially opening the file in whatever program you have set to open .txt files; one user may prefer notepad, another may prefer notepad++ or wordpad.  

I am marking this closed for now to move on to bigger issues, although feel free to comment and reopen if you have a better suggestion of how this feature should work.

**Comment by barrc** [comment]
I agree there are bigger issues but I have notepad set as my default program to open .txt files and it still tries to open the report files in Internet Explorer (which I don't think is set as my default program for any file extension).  

I looked at this issue at one point and found that changing from `webbrowser.open_new_tab(self.status_file_name)` to `webbrowser.open_new_tab(os.path.abspath(self.status_file_name))` did make the .txt file open in notepad on my machine, but I don't remember why that fixed the problem.
