### ISSUE TITLE
Allow user control of how objects are rendered on the map

### ISSUE THREAD

**Issue by MarkGrayRESPEC** [USEPA/SWMM-EPANET_User_Interface#16]
In MTP3r1, there is a window available that displays the rendering rules for the current layer (activated by the last tool button on the middle tool bar) but there is not yet a way to apply any changes made to the map.

**Comment by TongZhai** [comment]
This enhancement is implemented ([c229b99bb6595f0fbb4c86be5f603c611ed36c5c](https://github.com/USEPA/SWMM-EPANET_User_Interface/commit/c229b99bb6595f0fbb4c86be5f603c611ed36c5c)), now, a new symbology editor is implemented that allows users to change layer style and symbology.
