### ISSUE TITLE
SWMM_MTP4-r2_Measure distance or area

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#168]
- Doesn't display units
- Displays too many decimal points

**Comment by barrc** [comment]
Switching to and from the measure tool doesn't always work as expected.  If you've clicked on 'select region', clicking on 'measure' doesn't switch to 'measure'.  If you've clicked on 'measure', clicking on the other tools on this toolbar doesn't deselect 'measure'.

**Comment by barrc** [comment]
See #107 for toggle switch issue with EPANET

**Comment by PaulDudaRESPEC** [comment]
fixed along with #107
