### ISSUE TITLE
SWMM_MTP4-r2_Time steps interface

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#169]
If you have an inp file with a set routing step, it is sometimes not displayed in the time steps editor.

**Comment by PaulDudaRESPEC** [comment]
I tried to reproduce this, but I could not.

**Comment by PaulDudaRESPEC** [comment]
I tested this again and it seems to work as designed,  I'm going to close it.  barrc, if you continue to see a problem please feel free to reopen.

**Comment by barrc** [comment]
It's been a while but I was able to reproduce this with MTP6r2 and I have an idea for what the problem might be.  

Both UIs write routing steps to the inp file as hour:minute:seconds, even though they are displayed as seconds in the time editor box.  The old UI writes h:mm:s:
 ROUTING_STEP       	0:00:01

The new UI is expecting and writes hh:mm:ss:  (note leading zero for hours)
 ROUTING_STEP       	00:00:01

If you follow these steps:
- Create a file in the old UI with a routing step of 1 second
- Open that file in the new UI
- Open the time editor
- The routing step is shown as 0 seconds
- Try to run a simulation
- You'll get a crash because the new routing step is 0 seconds

I have an idea for fixing this; I will make a PR and request review.

**Comment by barrc** [comment]
I guess this is not really a bug, since a file created with the new UI will work with the new UI.  

But if we want to let users run files created with the old UI in the new UI, I think addressing this would help compatibility.  I'm open to other people's input!
