### ISSUE TITLE
SWMM_MTP4-r2_Units in object editors

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#171]
Units aren't handled in a consistent way in the object editors.  

Sometimes they are show US units even if you're in metric:
- Curves
- Snow packs
- Unit hydrographs
- Inflows
- Cross-sections
- Transects
- Initial buildup

Sometimes they skip units:
- Subcatchments
- Aquifers
- Junctions
- Outfalls
- Dividers
- Storage units
- Conduits
- Pumps
- Orifices
- Weirs
- Outlets

Sometimes they show both as options:
- Infiltration
- LID controls
- LID usage
- Land uses
- Groundwater flow

**Comment by PaulDudaRESPEC** [comment]
Cleaned up units labels in various forms
