### ISSUE TITLE
SWMM_MTP4-r2_Default values

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#173]
Some default values are different than in the old UI.  These are in two categories:
1. Defaults that are explicitly listed in the SWMM 5.1 user's manual, like the default infiltration model or the "can surcharge" parameter of a weir.
2. Defaults that populate the editors of old UI, but not explicitly listed in the user's manual, like LID control parameters or the coefficients for a functional curve for an outlet.

**Comment by PaulDudaRESPEC** [comment]
Updated all defaults to match those explicitly listed in the user's manual, and updated editors for the LID controls and others as suggested.
