### ISSUE TITLE
SWMM_MTP4-r2_Map tab

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#175]
Symbolizing by certain parameters doesn't work.  For subcatchments: area, width, % slope, % imperv, LID controls.  For nodes: invert elevation.  For links: max depth, roughness, slope.  

Show flow direction doesn't do anything.

If you symbolize by a given parameter, then change it back to none, the symbol stays.

I assumed changing the number next to the slider (see below) would speed up the visualization, but it didn't seem to.  Clicking the arrows did change the visualization, but then the arrow jumped either forward or backward.

![image](https://user-images.githubusercontent.com/13906772/34789597-af431d9a-f5f3-11e7-9323-b8bab9f1cbd3.png)

**Comment by barrc** [comment]
See #106

**Comment by PaulDudaRESPEC** [comment]
This issue is resolved, with the exception of the play speed control which is not yet implemented.  The rendering features have been tested with standard test runs and they now work as intended.
