### ISSUE TITLE
SWMM_MTP4-r2_Blank sections create Unnamed objects

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#178]
Some people work off inp file templates that have all possible sections, but leave the sections blank if they're not using that part of the model.  These files are parsed correctly by the old UI but cause problems by creating 'Unnamed' objects for snow packs, LID controls, and unit hydrographs.

**Comment by TongZhai** [comment]
@barrc please attach an example inp template file that contains all possible sections to this thread to help inp I/O QA effort.

**Comment by barrc** [comment]
@TongZhai See [here](https://github.com/ftt01/INPparser/blob/master/2D.inp)
