### ISSUE TITLE
SWMM_MTP4-r2_Editing time series plots

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#179]
The green check mark on the time series plot, which is supposed to let you edit the axes parameters, does nothing.  It works fine for the scatter plots.

**Comment by PaulDudaRESPEC** [comment]
Recent changes to src\Externals\swmm\outputapi\SMOutputSWIG.py allow testing of the time series plots, which now work as designed, including the editing of axis parameters, line colors, labels, etc.
