### ISSUE TITLE
SWMM_MTP4-r2_Time series viewer Copy, Save, and Print

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#183]
- File -> Copy does nothing
- File -> Save does nothing
- File -> Print does nothing
- Help does nothing

**Comment by PaulDudaRESPEC** [comment]
Help is fixed as part of issue #182, the File menu has been removed for now.  The Copy and Print functionalities will be kept as an open issue for future enhancement.

**Comment by barrc** [comment]
I think this issue can be closed; copy and print have been removed as well.
