### ISSUE TITLE
EPANET-MTP4r2 First Object in New File seems to always be centered

### ISSUE THREAD

**Issue by ucchejbb** [USEPA/SWMM-EPANET_User_Interface#184]
When selecting a node, tank or reservoir and placing it in a new space, it seems to always place that object in the center of the frame, regardless of where I click to place it. Subsequent objects are placed correctly, and deleting that object and placing it again seems to work fine.

**Comment by barrc** [comment]
The same behavior occurs in the SWMM UI.  Closed issue #63 says this behavior is by design.

**Comment by PaulDudaRESPEC** [comment]
Since issue #63 is closed, this one should be marked closed too.

**Comment by eladsal** [comment]
Well, #63 should have been closed. This is not what the user expects.
