### ISSUE TITLE
EPANET-MTP4r2 - Difficulty connecting pipes to nodes

### ISSUE THREAD

**Issue by ucchejbb** [USEPA/SWMM-EPANET_User_Interface#185]
When working with a larger network, I zoomed in to better see the nodes, but when I clicked on a starting node the red indicator of a pipe showed the pipe originating from off the screen. This new pipe failed to connect easily to a node, which was previously described in Issue #95. [It seems as if this issue was closed, so maybe the updated release would correct this failure to finalize a pipe behavior]

Also, once pipes were created, they showed up in a window by themselves (i.e., no other existing pipes were reflected in this window) and clicking on those pipe IDs did not open their property windows. Navigating back to the ["Project" Tab >> Pipes] showed all the pipes including the new ones, but this behavior was confusing.

**Comment by PaulDudaRESPEC** [comment]
Since Issue #95 is closed I think this one should be closed too.
