### ISSUE TITLE
Map does not appear on "clean" copy of Windows

### ISSUE THREAD

**Issue by MarkGrayRESPEC** [USEPA/SWMM-EPANET_User_Interface#19]
EPANET-UI-MTP3r1, when installed on a fresh virtual machine, is not displaying the map. Since we have seen the map working with this package on other computers, this is probably because the map has a dependency on something that is not in our install package but which is commonly installed by other software, so computers that are in regular use already have what is needed.

The dependency can probably be located by using a dependency checking tool while the application is running and correctly displaying the map and comparing results with when it is running and not displaying the map.

Since this is not a problem so far for early adopters this is not the top priority.

**Comment by PaulDudaRESPEC** [comment]
Closing this so it is no longer shows as an active issue, since the packaging is being redone for the python3 version.
