### ISSUE TITLE
SWMM_MTP4-r2_Program crashes if you create new during animation

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#194]
To replicate:
- Run a model
- Go to the map tab and symbolize subcatchments by infiltration
- Press play
- File -> New (the animation timer will keep going)
- Draw a subcatchment

The animation timer should stop when the user does File -> New and the dialog should not stay open.

**Comment by PaulDudaRESPEC** [comment]
The steps listed in the description have been tested with the commit above and there is no longer a bug.
