### ISSUE TITLE
Import of Rainfall Elements, A file Raingage is imported as a Time Series Raingage

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/SWMM-EPANET_User_Interface#196]
If you import the EPA SWMM 5 Continuous Simulation Tutorial the model cannot be run as the File information is improperly interpreted as a Time Series  

  
  ERROR 209: undefined object * at line 59 of [RAINGAGE] section:
  GAGE1           	INTENSITY	1.000000	1.000000	TIMESERIES	*

**Comment by dickinsonre** [comment]
Here is the model
[TITLE]
;;Project Title/Notes
Scenario Run :  BASE

[OPTIONS]
;;Option             Value
FLOW_UNITS           CFS
INFILTRATION         MODIFIED_GREEN_AMPT
FLOW_ROUTING         KINWAVE
LINK_OFFSETS         DEPTH
MIN_SLOPE            0
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO

START_DATE           01/01/1998
START_TIME           00:00:00
REPORT_START_DATE    01/01/1998
REPORT_START_TIME    00:00:00
END_DATE             01/01/2000
END_TIME             12:00:00
SWEEP_START          01/01
SWEEP_END            12/31
DRY_DAYS             5.000000
REPORT_STEP          00:05:00
WET_STEP             00:15:00
DRY_STEP             01:00:00
ROUTING_STEP         0:05:00 

INERTIAL_DAMPING     PARTIAL
NORMAL_FLOW_LIMITED  SLOPE
FORCE_MAIN_EQUATION  H-W
VARIABLE_STEP        0.75
LENGTHENING_STEP     0
MIN_SURFAREA         12.557
MAX_TRIALS           8
HEAD_TOLERANCE       0.005
SYS_FLOW_TOL         5
LAT_FLOW_TOL         5
MINIMUM_STEP         0
THREADS              1

[EVAPORATION]
;;Data Source    Parameters
;;-------------- ----------------
CONSTANT         0.0
DRY_ONLY         NO

[RAINGAGES]
;;Name           Format    Interval SCF      Source    
;;-------------- --------- ------ ------ ----------
GAGE1            INTENSITY 1.000000 1.000000 FILE       "sta310301.dat"  310301     IN   

[SUBCATCHMENTS]
;;Name           Rain Gage        Outlet           Area     %Imperv  Width    %Slope   CurbLen  SnowPack        
;;-------------- ---------------- ---------------- -------- -------- -------- -------- -------- ----------------
S1               Gage1            J1               4.000000 50.000000 400.000000 0.500000 0.000000                 
S2               Gage1            J2               4.000000 50.000000 400.000000 0.500000 0.000000                 
;  New Subcatchment
S3               Gage1            J3               4.000000 25.000000 400.000000 0.500000 0.000000                 

[SUBAREAS]
;;Subcatchment   N-Imperv   N-Perv     S-Imperv   S-Perv     PctZero    RouteTo    PctRouted 
;;-------------- ---------- ---------- ---------- ---------- ---------- ---------- ----------
S1               0.010000   0.100000   0.050000   0.050000   100.000000 OUTLET    
S2               0.010000   0.100000   0.050000   0.050000   100.000000 OUTLET    
S3               0.010000   0.100000   0.050000   0.050000   100.000000 OUTLET    

[INFILTRATION]
;;Subcatchment   Suction    Ksat       IMD       
;;-------------- ---------- ---------- ----------
S1               3.5        .5         .25       
S2               3.5        .5         .25       
S3               3.5        0.5        25        

[AQUIFERS]
;;Name           Por    WP     FC     Ksat   Kslope Tslope ETu    ETs    Seep   Ebot   Egw    Umc    ETupat 
;;-------------- ------ ------ ------ ------ ------ ------ ------ ------ ------ ------ ------ ------ ------
CALSAMPLE        0.500000 0.150000 0.300000 10.000000 0.000000 15.000000 0.350000 0.350000 0.002000 0.000000 0.000000 0.250000       

[GROUNDWATER]
;;Subcatchment   Aquifer          Node             Esurf  A1     B1     A2     B2     A3     Dsw    Egwt   Ebot   Wgr    Umc   
;;-------------- ---------------- ---------------- ------ ------ ------ ------ ------ ------ ------ ------ ------ ------ ------

[JUNCTIONS]
;;Name           Elevation  MaxDepth   InitDepth  SurDepth   Aponded   
;;-------------- ---------- ---------- ---------- ---------- ----------
J1               96.000000  4.000000   0.000000   0.000000   0.000000  
J2               90.000000  4.000000   0.000000   0.000000   0.000000  
J3               93.000000  4.000000   0.000000   0.000000   0.000000  
J4               88.000000  4.000000   0.000000   0.000000   0.000000  

[OUTFALLS]
;;Name           Elevation  Type       Stage Data       Gated    Route To        
;;-------------- ---------- ---------- ---------------- -------- ----------------
OUT1             85.000000  FREE                        NO                       

[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow   
;;-------------- ---------------- ---------------- ---------- ---------- ---------- ---------- ---------- ----------
C1               J1               J2               400.000000 0.010000   0.000000   0.000000   0.000000   0.000000  
C2               J2               J4               400.000000 0.010000   0.000000   0.000000   0.000000   0.000000  
C3               J3               J4               400.000000 0.010000   0.000000   0.000000   0.000000   0.000000  
;  New Conduit
C4               J4               OUT1             400.000000 0.010000   0.000000   0.000000   0.000000   0.000000  

[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   
;;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------
C1               CIRCULAR     1.000000         0.000000   0.000000   0.000000   1          0         
C2               CIRCULAR     1.000000         0.000000   0.000000   0.000000   1          0         
C3               CIRCULAR     1.000000         0.000000   0.000000   0.000000   1          0         
C4               CIRCULAR     1.500000         0.000000   0.000000   0.000000   1          0         

[LOSSES]
;;Link           Kentry     Kexit      Kavg       Flap Gate  Seepage   
;;-------------- ---------- ---------- ---------- ---------- ----------
C1               0.000000   0.000000   0.000000   NO         0.000000  
C2               0.000000   0.000000   0.000000   NO         0.000000  
C3               0.000000   0.000000   0.000000   NO         0.000000  
C4               0.000000   0.000000   0.000000   NO         0.000000  

[CONTROLS]




[POLLUTANTS]
;;Name           Units  Crain      Cgw        Crdii      Kdecay     SnowOnly   Co-Pollutant     Co-Frac    Cdwf       Cinit     
;;-------------- ------ ---------- ---------- ---------- ---------- ---------- ---------------- ---------- ---------- ----------
TSS              MG/L   0.000000   0.000000   0.000000   0.000000   NO         *                0.000000   0.000000   0.000000  
LEAD             UG/L   0.000000   0.000000   0.000000   0.000000   NO         TSS              0.250000   0.000000   0.000000  

[LANDUSES]
;;               Sweeping   Fraction   Last      
;;Name           Interval   Available  Swept     
;;-------------- ---------- ---------- ----------
;  Residential Land Use
RESIDENTIAL      0.000000   0.000000   0.000000  
;  Undeveloped Land Use
UNDEVELOPED      0.000000   0.000000   0.000000  

[COVERAGES]
;;Subcatchment   Land Use         Percent   
;;-------------- ---------------- ----------
S1               RESIDENTIAL      75.000000 
S1               UNDEVELOPED      25.000000 
S2               RESIDENTIAL      75.000000 
S2               UNDEVELOPED      25.000000 
S3               RESIDENTIAL      25.000000 
S3               UNDEVELOPED      75.000000 

[LOADINGS]
;;Subcatchment   Pollutant        Buildup   
;;-------------- ---------------- ----------

[BUILDUP]
;;Land Use       Pollutant        Function   Coeff1     Coeff2     Coeff3     Per Unit  
;;-------------- ---------------- ---------- ---------- ---------- ---------- ----------
RESIDENTIAL      TSS              POW        50.000000  1.000000   1.000000   AREA      
RESIDENTIAL      LEAD             NONE       10.000000  2.000000   0.500000   AREA      
UNDEVELOPED      TSS              POW        25.000000  0.500000   1.000000   AREA      
UNDEVELOPED      LEAD             NONE       10.000000  2.000000   0.500000   AREA      

[WASHOFF]
;;Land Use       Pollutant        Function   Coeff1     Coeff2     SweepRmvl  BmpRmvl   
;;-------------- ---------------- ---------- ---------- ---------- ---------- ----------
RESIDENTIAL      TSS              EMC        100.000000 0.000000   0.000000   0.000000  
RESIDENTIAL      LEAD             EXP        0.200000   0.300000   50.000000  20.000000 
UNDEVELOPED      TSS              EMC        50.000000  0.000000   0.000000   0.000000  
UNDEVELOPED      LEAD             EXP        0.200000   0.300000   50.000000  20.000000 

[HYDROGRAPHS]
;;Hydrograph     Rain Gage/Month  Response R        T        K        Dmax     Drecov   Dinit   
;;-------------- ---------------- -------- -------- -------- -------- -------- -------- --------
RDIIUJH          GAGE1           
RDIIUJH          All              Short    0.000000 0.080000 1.000000 0.000000 0.000000 0.000000
RDIIUJH          All              Medium   0.000000 0.000000 0.500000 0.000000 0.000000 0.000000
RDIIUJH          All              Long     0.000000 0.000000 1.000000 0.000000 0.000000 0.000000


[TIMESERIES]
;;Name           Date       Time       Value     
;;-------------- ---------- ---------- ----------
;  New Time Series
TS1                         0          0.000000  
TS1                         1          0.500000  
TS1                         2          1.000000  
TS1                         3          0.750000  
TS1                         4          0.500000  
TS1                         5          0.250000  
TS1                         6          0.000000  
;
TSCAL            03/17/2005 00:15      0.000000  
TSCAL            03/17/2005 01:00      0.000000  
TSCAL            03/17/2005 01:15      0.407000  
TSCAL            03/17/2005 01:30      1.229000  
TSCAL            03/17/2005 01:45      1.598000  
TSCAL            03/17/2005 02:00      1.718000  
TSCAL            03/17/2005 02:15      2.013000  
TSCAL            03/17/2005 02:30      2.094000  
TSCAL            03/17/2005 02:45      2.116000  
TSCAL            03/17/2005 03:00      2.121000  
TSCAL            03/17/2005 03:15      2.664000  
TSCAL            03/17/2005 03:30      2.794000  
TSCAL            03/17/2005 03:45      2.823000  
TSCAL            03/17/2005 04:00      2.829000  
TSCAL            03/17/2005 04:15      2.288000  
TSCAL            03/17/2005 04:30      2.165000  
TSCAL            03/17/2005 04:45      2.134000  
TSCAL            03/17/2005 05:00      2.126000  
TSCAL            03/17/2005 05:15      2.391000  
TSCAL            03/17/2005 05:30      2.457000  
TSCAL            03/17/2005 05:45      2.472000  
TSCAL            03/17/2005 06:00      2.476000  
TSCAL            03/17/2005 06:15      2.531000  
TSCAL            03/17/2005 06:30      2.544000  
TSCAL            03/17/2005 06:45      2.547000  
TSCAL            03/17/2005 07:00      2.548000  
TSCAL            03/17/2005 07:15      2.768000  
TSCAL            03/17/2005 07:30      2.817000  
TSCAL            03/17/2005 07:45      2.828000  
TSCAL            03/17/2005 08:00      2.830000  
TSCAL            03/17/2005 08:15      2.887000  
TSCAL            03/17/2005 08:30      2.899000  
TSCAL            03/17/2005 08:45      2.901000  
TSCAL            03/17/2005 09:00      2.902000  
TSCAL            03/17/2005 09:15      3.701000  
TSCAL            03/17/2005 09:30      3.858000  
TSCAL            03/17/2005 09:45      3.886000  
TSCAL            03/17/2005 10:00      3.892000  
TSCAL            03/17/2005 10:15      3.318000  
TSCAL            03/17/2005 10:30      3.212000  
TSCAL            03/17/2005 10:45      3.191000  
TSCAL            03/17/2005 11:00      3.186000  
TSCAL            03/17/2005 11:15      3.047000  
TSCAL            03/17/2005 11:30      3.018000  
TSCAL            03/17/2005 11:45      3.012000  
TSCAL            03/17/2005 12:00      3.011000  
TSCAL            03/17/2005 12:15      3.873000  
TSCAL            03/17/2005 12:30      4.037000  
TSCAL            03/17/2005 12:45      4.066000  
TSCAL            03/17/2005 13:00      4.071000  
TSCAL            03/17/2005 13:15      3.781000  
TSCAL            03/17/2005 13:30      3.730000  
TSCAL            03/17/2005 13:45      3.720000  
TSCAL            03/17/2005 14:00      3.719000  
TSCAL            03/17/2005 14:15      3.287000  
TSCAL            03/17/2005 14:30      3.206000  
TSCAL            03/17/2005 14:45      3.189000  
TSCAL            03/17/2005 15:00      3.186000  
TSCAL            03/17/2005 15:15      2.905000  
TSCAL            03/17/2005 15:30      2.847000  
TSCAL            03/17/2005 15:45      2.835000  
TSCAL            03/17/2005 16:00      2.832000  
TSCAL            03/17/2005 16:15      2.289000  
TSCAL            03/17/2005 16:30      2.165000  
TSCAL            03/17/2005 16:45      2.134000  
TSCAL            03/17/2005 17:00      2.126000  
TSCAL            03/17/2005 17:15      1.865000  
TSCAL            03/17/2005 17:30      1.796000  
TSCAL            03/17/2005 17:45      1.777000  
TSCAL            03/17/2005 18:00      1.772000  
TSCAL            03/17/2005 18:15      1.520000  
TSCAL            03/17/2005 18:30      1.448000  
TSCAL            03/17/2005 18:45      1.426000  
TSCAL            03/17/2005 19:00      1.419000  
TSCAL            03/17/2005 19:15      1.179000  
TSCAL            03/17/2005 19:30      1.102000  
TSCAL            03/17/2005 19:45      1.076000  
TSCAL            03/17/2005 20:00      1.067000  
TSCAL            03/17/2005 20:15      0.637000  
TSCAL            03/17/2005 20:30      0.481000  
TSCAL            03/17/2005 20:45      0.412000  
TSCAL            03/17/2005 21:00      0.380000  
TSCAL            03/17/2005 21:15      0.210000  
TSCAL            03/17/2005 21:30      0.129000  
TSCAL            03/17/2005 21:45      0.085000  
TSCAL            03/17/2005 22:00      0.060000  
TSCAL            03/17/2005 22:15      0.044000  
TSCAL            03/17/2005 22:30      0.033000  
TSCAL            03/17/2005 22:45      0.026000  
TSCAL            03/17/2005 23:00      0.021000  
TSCAL            03/17/2005 23:15      0.017000  
TSCAL            03/17/2005 23:30      0.014000  

[REPORT]
;;Reporting Options
INPUT      NO
CONTROLS   NO
SUBCATCHMENTS ALL
NODES ALL
LINKS ALL

[TAGS]

[MAP]
DIMENSIONS 86.662 569.448 602.626 872.547
Units      None

[COORDINATES]
;;Node           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
J1               579.173            780.314           
J2               579.173            583.452           
J3               330.956            783.167           
J4               330.956            583.452           
OUT1             110.115            583.225           

[VERTICES]
;;Link           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------

[Polygons]
;;Subcatchment   X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
S1               396.576            841.655           
S1               500.713            841.655           
S1               500.713            756.063           
S1               396.576            756.063           
S1               396.576            758.916           
S1               396.576            841.655           
S2               396.576            690.442           
S2               506.419            690.442           
S2               506.419            609.130           
S2               396.576            609.130           
S2               396.576            609.130           
S2               396.576            690.442           
S3               178.317            845.934           
S3               275.321            845.934           
S3               275.321            764.622           
S3               178.317            764.622           
S3               178.317            763.195           
S3               178.317            845.934           

[SYMBOLS]
;;Gage           X-Coord            Y-Coord           
;;-------------- ------------------ ------------------
GAGE1            318.120            858.770

**Comment by barrc** [comment]
See #136

**Comment by dickinsonre** [comment]
Thanks, i see you already documented this issue.
