### ISSUE TITLE
EPANET_MTP4-r2_Map Label Editor

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#197]
Map Label Editor is not working properly and it doesn't change the label font size nor its boldness and italics. Text section works fine but Undo/Redo option doesn't work with it.

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by PaulDudaRESPEC** [comment]
Anchor nodes, fonts, font size, bold and italics are now all implemented and tested.

**Comment by TongZhai** [comment]
The label styling function would need to be implemented and moved to the general GIS layer styling context menu so as not to interfere with other functions such as building model via import or toggle with default styling.

**Comment by TongZhai** [comment]
Now users can simply right-mouse click on 'Map Labels' (SWMM) and 'Labels' (EPANET) layer and choose 'Change Style', which will bring up label text style editor to change a variety of styles, including color, size, and font family.
