### ISSUE TITLE
EPANET_MTP4-r2_Select vertex icon linkage with menu

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#200]
When the 'select vertex' under EDIT menu is clicked, the 'select vertex' icon in the selection toolbar does not change as selected. the 'select vertex' icon in the selection toolbar is supposed to be linked to menu selection.

**Comment by rjanke20** [comment]
Also,  vertex points do not appear on the pipe when clicking vertex mode.  See also #121.
--
