### ISSUE TITLE
EPANET_MTP4-r2_High_Junction ID change breaks the network topology

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#202]
The pipe ID change works fine, but the Junction ID (or Name) change breaks the network connection topology. Node name changes have often happened. After changing Name in junction editor, the connected pipe are disappeared. For instance, Junction 20 is changed to 20j. The pipes are disappeared. Undo does not work.  
![image](https://user-images.githubusercontent.com/2411770/35403613-44bbe95c-01ce-11e8-90dc-c39a61ae561a.png)

**Comment by ucchejbb** [comment]
Also, the pipe does not reappear when I attempt to correct end node of the pipe to match the new nodeID.

**Comment by TongZhai** [comment]
@woohn @ucchejbb This bug is directly related to the recently closed issue #195, fixes and code improvements on that issue contain fixes for this bug. Basically, now, the UI will detect duplicate names in the property editor, also properly handles renaming of any model objects.
