### ISSUE TITLE
EPANET-MTP4r2-Layers Tab-Project Explorer

### ISSUE THREAD

**Issue by ucchejbb** [USEPA/SWMM-EPANET_User_Interface#207]
In playback mode something that is toggled off turns itself back on after the next timestep of the playback. 

Toggling some values off resulted in shifts in text for other objects.

Toggling the "group" on or off does not work as expected. When all selections under "tanks" were manually de-selected the main "check" next to tanks remained checked, clicking that turned the check off, but clicking again didn't re-check all the sub-boxes. I would expect the main check box to act as a group selector to turn things back on again. The selector does turn things off/on as a group if all the subcategories were checked to begin with.

**Comment by TongZhai** [comment]
@ucchejbb In short, to check all/uncheck all in a group, one needs to hold down the Ctrl key, then click on the group node's checkbox. This recent QGIS improvement has actually been [thoroughly debated on QGIS git repo](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/86). I think Ctrl-click suffices our needs in this software.

**Comment by TongZhai** [comment]
@ucchejbb In short, to check all/uncheck all in a group, one needs to hold down the Ctrl key, then click on the group node's checkbox. This QGIS enhancement has actually been [thoroughly debated on QGIS git repo](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/86). I think Ctrl-click suffices our needs in this software.

**Comment by TongZhai** [comment]
@ucchejbb with the above two updates, now users' labeling choice will be remembered when they right click on a layer to choose to label by name or value or turn it off. This choice will be applied during playback mode.
