### ISSUE TITLE
EPANET_MTP4r2_High_Plot windows does not disappear automatically after closing the main program

### ISSUE THREAD

**Issue by woohn** [USEPA/SWMM-EPANET_User_Interface#208]
Plot windows do not close automatically after closing the main program. When the user makes a plot, the UI created new windows dialogue by calling python plot window which is located outside the program. This means it loaded in the memory inefficiently and operated independently.

**Comment by TongZhai** [comment]
@woohn The update above will close incidences of pyplot (windows etc) when exiting the main program.
