### ISSUE TITLE
EPANET_MTP4r2_Edit-Menu_Edit-Object_No-Group-Edit-Option_Low 

### ISSUE THREAD

**Issue by terrahaxton** [USEPA/SWMM-EPANET_User_Interface#210]
Feature request: Include the Group Edit menu option in this version of the UI, since it would be easier to change the value for all selected objects, rather than having to edit them individually in the editor by using the tab function

**Comment by rjanke20** [comment]
Also, it seems like “Edit Object…” does not always enable for node or pipe selection
--

**Comment by PaulDudaRESPEC** [comment]
I did some testing and the "Edit Object..." menu option seems to appear enabled whenever appropriate.

**Comment by TongZhai** [comment]
@terrahaxton @rjanke20 The way the "group edit" operation works is that users first activate "Select Region" tool and draw a polygon around the model elements of their interest on the map, this will select every elements inside the polygon. Then, users are to choose "Edit Object..." menu option, this will bring up a dropdown listing of all categories of model elements being selected, users can pick a category of elements to bring up their attribute editor for editing.
