### ISSUE TITLE
EPANET_MTP4r2_ View-Menu_Dimensions_High

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#213]
Dimensions can be removed or changed arbitrarily after working on a project, which when viewed in original EPANET UI can make viewing difficult.  (Fortunately user can select "Auto-Resize" in original UI)
--

--

**Comment by PaulDudaRESPEC** [comment]
Testing in dev-ui-py3qt5 shows this functionality is now working.
