### ISSUE TITLE
EPANET_MTP4r2_ View-Backdrop_Align_Resize_High

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#214]
Load backdrop map - Align & Resize - Nothing happens, does not seem to work.

**Comment by rjanke20** [comment]
Also, loaded backdrop map can be misaligned with network model; whereas for same model/backdrop (Micropolis) they are not misaligned in the Original EPANET UI.

**Comment by TongZhai** [comment]
@rjanke20 The original backdrop operations are for displaying a raster based "map", these functionalities are offered in the new UI through "Add a raster layer" (toolbar icon) function, and users can add as many raster base maps, which will all be put in the "Base Maps" layer group, where users can turn on/off any layer or remove them all together. These maps are treated as any other maps that users can zoom and pan. The update above implements the layer removal operations and other supporting functions. Hence, the original backdrop operations are removed from the main menu dropdown menu. Documentation should be updated per this improved functionality.
