### ISSUE TITLE
EPANET_MTP4r2_ Project-Menu_Summary_High

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#216]
If the user modifies the EPANET Project Summary, e.g., adds title, changes are not preserved, unless specifically saved.  User is not prompted to save different inp file.

**Comment by TongZhai** [comment]
@rjanke20 This is part of the feature request #286, changes such as summary title etc would be detected and prompt users to save. We will need to think how to do this in a coordinated fashion as this will be needed for all aspects of the model, UI, model elements, comments, etc etc.
