### ISSUE TITLE
EPANET_MTP4r2_ Project-Menu_Run-Simulation-Too-Many_Files_Medium

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#219]
Running a simulation creates 4 files automatically.  E.g., consider the inp file named, “12-4-test.inp”.  After running a simulation 4 files are created, each with the prefix:  (1) 12-4-test_trial_12_16_20.inp, (2) .out, (3) _status.txt, (4) 12-4-test.ini and each with a suffix time stamp.  Non of these files are temporary files.

This really clogs up the user's directory, specifically the directory from where the inp was opened.

**Comment by TongZhai** [comment]
@rjanke20 this is essentially the same issue as #101, so will be addressed as one

**Comment by TongZhai** [comment]
@rjanke20 now each simulation will use temporary files and will be removed after 'New', 'Exit', or rerun
