### ISSUE TITLE
Error 437, cannot find output file

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#22]
I was able to get MTP3r2 to run by running as Administrator.  The run seemingly completes but generates the subject error and leaves the user unable to see simulation results.  Status report is produced, but so is "Error opening model output- EPANET output error #437".  Also, the "Run was successful" prompt is produced.

**Comment by eladsal** [comment]
I'm getting the same error for some networks. Some runs well and can show results.

**Comment by TongZhai** [comment]
[This is fixed](https://github.com/USEPA/SWMM-EPANET_User_Interface/pull/77)
