### ISSUE TITLE
EPANET_MTP4r2_ Project-Menu_Run-Stimulation_High

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#225]
Run Simulation, either from the "Standard Toolbar" or "Project" Menu can result in a network being run and then having problems or failures (e.g.., disconnect) and these problems seem to be reported only in the status report while "Run was successful" still seems to print to the screen regardless of simulation outcome.

![image](https://user-images.githubusercontent.com/2397585/35457491-18a1256a-02a7-11e8-9f19-82510f921075.png)
 

In the Original UI for EPANET, "Run was successful" is reserved for only those models/simulations that run without errors or warnings.

**Comment by TongZhai** [comment]
@rjanke20 The EPANET simulation runtime error/warning handling process is reworked and it matches the behavior of the original EPANET
