### ISSUE TITLE
EPANET_MTP4r2_ Standard-Toolbar_Create-statistic-report_Medium

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#228]
Nothing happens, if no statistic is chosen (Project Tab/Options/Times).  If statistic is chosen, e.g., "Maximum", then error message, "SWMM output error calling ENR_newOutValueSeries: EPANET  output error #422". Additionally, "Run was successful" status is given.

**Comment by PaulDudaRESPEC** [comment]
I'm taking the statistical output button off the UI for EPANET, as the statistics report is a SWMM thing.  However that error 422 needs to be investigated further, as it appears to be a problem with the EPANET output wrapper.

**Comment by PaulDudaRESPEC** [comment]
see also issue #110

**Comment by TongZhai** [comment]
@rjanke20 The statistic reporting is for SWMM, evidently trying this on EPANET's output will lead to error. So, removing its access from SWMM's UI should address this issue.
