### ISSUE TITLE
EPANET_MTP4r2_ Map-Toolbar_Viewing-network_High

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#229]
Viewing the network in the Project Explorer, Map Tab and Layers Tab can easily result in the UI program shutting down.  There is something buggy about the Map and Layers.

**Comment by TongZhai** [comment]
@rjanke20 User testing is one of the most important ways of exposing problems in software. Usually,  certain combination of operations in certain sequence could lead to crash, it is important for users to remember what was the sequence of things that were being performed before the crash, such information can help us reproduce the crash for fixing. So, more specific details would be needed when you encounter a failure to be included in bug/issue report.
