### ISSUE TITLE
Exception from changing SWMM model flow units

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#237]
When changing the model's flow units using the drop down box on the lower bar of the SWMM UI to CMS, LPS, or MLD, I get the following exception:

```
Traceback (most recent call last):

File "C:/Users/cbarr02/Desktop/GitHub/SWMM-EPANET_User_Interface/src/ui/SWMM/frmMainSWMM.py", line 452, in cbFlowUnits_currentIndexChanged
self.project.metric = self.project.options.hydraulics.flow_units in core.swmm.options.general.flow_units_metric
AttributeError: 'General' object has no attribute 'hydraulics'
```

**Comment by michelleannesimon** [comment]
Curves to do change to default units.  Instead of cms it should be lps

![image](https://user-images.githubusercontent.com/26123284/65269484-3f8cbf80-dae7-11e9-854f-ab7fa97bd5df.png)

**Comment by PaulDudaRESPEC** [comment]
Fix for curve units is fixed in the upcoming MTP
