### ISSUE TITLE
SWMM project defaults don't handle metric units

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#238]
If your project is in metric units, should get the value associated with the metric default.  Issue #173 also addresses differences between the default values and the values listed in the user's manual.

**Comment by PaulDudaRESPEC** [comment]
Upon closer examination, this issue is an enhancement, not a bug.  The behavior of the new UI is the same as it was in the older SWMM UI, and it is assumed that the default values provided are in the unit system being used.

**Comment by barrc** [comment]
I think in the old UI, if you change the unit system, different values are populated for a few of the parameters on the Dynamic Wave tab of the Simulation Options.  But I don't recall if there are any other differences based on unit system, so it's correct to label the broad statement I initially posted as an enhancement.

US units:
![image](https://user-images.githubusercontent.com/13906772/50245930-b9412280-0388-11e9-8b99-1de6538fe0aa.png)

Metric units:
![image](https://user-images.githubusercontent.com/13906772/50245966-d249d380-0388-11e9-9748-10020c6be800.png)

**Comment by dickinsonre** [comment]
Yes, that is true @barrc but it is the current GUI you are describing or the Delphi Pascal UI.  Labels and defaults change based on the units of the model.

**Comment by barrc** [comment]
@dickinsonre are you saying the labels and defaults change based on the units of the model in the current UI or the Delphi UI?  It sounds like Paul was saying the labels/defaults don't change in the Delphi UI.  I might be confused here.

**Comment by PaulDudaRESPEC** [comment]
@barrc Yes, now we see where there are differences in the default values for a few of the dynamic wave settings; thanks for pointing that out -- we'll be sure to fix those.  In most instances the labels in the new UI change depending on the units system, but we see there are some of those that need to be fixed too.

**Comment by PaulDudaRESPEC** [comment]
OK, fixed the dynamic wave options so that the labels and defaults change appropriately.

**Comment by PaulDudaRESPEC** [comment]
Found other instances where the labels were not changing appropriately on the climatology tabs, those are now fixed.  All labeling now switches back and forth from english to metric appropriately.

**Comment by barrc** [comment]
I think this can be closed now; the labels switch back and forth and the behavior is consistent with the Delphi GUI.  We can always revisit later.
