### ISSUE TITLE
SWMM can't edit subcatchment vertices

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#239]
A change since the MTP4-r2 release has made it so that clicking the 'edit vertex' button does not allow you to edit subcatchment vertices.  Instead a pop-up comes up saying 'Need to select a GIS layer first'.

**Comment by TongZhai** [comment]
@barrc this is actually an improvement from the previous MTP releases where only polygon's vertices can be edited. In this new improvement, the user is asked to first click to select a model GIS layer from the 'layer' tab, then click on the vertex edit toolbar button to display all vertices of that model layer to be edited (double click to add, right click to delete, drag to move), this works for both lines or polygons.

**Comment by barrc** [comment]
@TongZhai thanks for the explanation.
