### ISSUE TITLE
EPANET - Patterns editor can cut off patterns

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#241]
The EPANET patterns editor is limited to 24 entries.  If you have an existing model with a pattern with more than 24 entries (for example [Net2.inp](https://github.com/USEPA/SWMM-EPANET_User_Interface/blob/master/test/core/epanet/Examples/Net2.inp) included in this repo), and open it in the patterns editor, the pattern will be clipped when you run the model.

See #125 and #135 for clipped data from existing models in SWMM.

**Comment by barrc** [comment]
The initial issue should be fixed with #251 but this editor probably also needs a method to let the user add new pattern entries.

**Comment by PaulDudaRESPEC** [comment]
Committed a fix to allows adding additional entries into dev-ui-py3qt5, issued pull request
