### ISSUE TITLE
Running with Python3: ImportError: No module named 'ui'

### ISSUE THREAD

**Issue by quimperval** [USEPA/SWMM-EPANET_User_Interface#245]
Before any other thing, I must say that I'm a beginnner with Python and that I'm trying to run the GUI with Linux Debian Stretch and I've installed all dependencies and packages to run the Gui developed with python. 
When I want to start the gui with 
`python3 frmMain.py`
I receive the next error. 
`Traceback (most recent call last):`
`  File "frmMain.py", line 16, in <module>`
`    from ui.frmGenericPropertyEditor import frmGenericPropertyEditor`
`ImportError: No module named 'ui'`

I don't know if it is related with the Python version or what? 
Because I downloaded the source and there were some messages about the print and parentheses needed for python3, so I made the changes. I've tried to change the name to frmGenericPropertyEditor.ui but nothing happens. 

Or there is another method to run the GUI, wich I don't know?

Thanks in advance.

**Comment by ehsanMa86** [comment]
The first thing as you already mentioned, software is based on the python2. If you have a windows based machine, it would be better to run it with pyCharm and instruction given for developers on the wiki. 
https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Getting-Started-as-a-Developer

**Comment by quimperval** [comment]
Thanks a Lot!!1
