### ISSUE TITLE
The instruction "Getting Started as a Developer" has become outdated.

### ISSUE THREAD

**Issue by Yust11135** [USEPA/SWMM-EPANET_User_Interface#249]
Dear colleagues,

Please help. 
I try to use https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Getting-Started-as-a-Developer 

I spent 2 weeks trying to run frmMainEPANET.py.
A few months ago I was able to install and run everything according to the instructions.
But now I think something has changed in the installer QGis.

Could you please update instruction? The last update was on 2 Feb 2017.

Thanks in advance.

**Comment by michaeltryby** [comment]
@Yust11135 What was the nature of the problem you were having configuring your development environment?

**Comment by samhatchett** [comment]
This is a huge problem. I spent upwards of 4 hrs alongside 2 other developers this week, with both windows and mac machines, trying to get this to build on _any_ platform. No dice.

With better getting-started documentation (preferably cross plat), I know there are a handful of people willing and able to help fix bugs - but I've got no assurance that the version in the repo is the one actually used to build the testing release, or that anybody really knows how to configure the dev environment.

**Comment by michaeltryby** [comment]
I have encountered this problem myself and understand that it is a problem. I can assure you that the version in the repo was used to build the MTP releases. What I understand about what happened is that  OSGeo4W got updated and the developer kept their original setup and didn't realize the update had broken anything. 

The root cause of the problem is OSGeo4W. It is complicated, bloated, and frozen at Python 2.7.5. We have to jump through all kinds of hoops just to get PyQGIS and its dependencies installed. QGIS is organized as a C++ application that provides Python scripting support. Python is frozen and version 2.7.5 so a whole bunch of plugins don't have to be rewritten. We are writing a Python application and would like to use PyQGIS as if it were a first class Python package. But its not. 

As I see it, the real solution to this problem, is to create a PyQGIS Python package and eliminate the necessity of using OSGeo4W to satisfy these dependencies. I think this is completely doable, but would be challenging.

**Comment by michaeltryby** [comment]
During the packaging process, we are pulling out only the needed dependencies from the OSGeo4W developer setup for inclusion in the installer. What if we did this upfront instead? Created a Python package containing only the QGIS dlls, their dependencies, and Python wrappers. Only what our UI application needed packaged as a canonical Python package. The need to lug around OSGeo4W would be completely eliminated.

**Comment by Yust11135** [comment]
@michaeltryby @samhatchett  Thanks for the quick reply and thanks for the support.

I agree I think the problem with QGIS.
The first problem in item 7 - Select Packages (section Install QGIS) 
I think that specified packages are not enough. And the second problem with paths. 
Specified paths, not enough too. 

Step by step.
1. Download from the site OSGeo4W Network Installer (64bit)
Download Site (first site on the list) http://osgeo4w-oslandia.com

Selected packages like an instruction (All packages with default flag (Skip) and specifyed 
below packages find in search field and select the latest version):
-command line: python-core (ver2.7.5-3),python-tools (ver2.7.5-1), 
python-tcltk (ver2.7.5-1), setup(ver1.0.7-16), shell(ver1.0.2-2).
-desktop: qgis-full(ver3.0-1).
-libs: gdal-filegdb (ver2.2.4-1), python-devel(ver2.7.5-1), setuptools(ver0.9.8-1).

2. PATHs like in instruction.

3.Open an OSGeo4W Shell. 
3.1 Try python -m pip install --upgrade pip, answer from the shell:
` run o-help for a list of available commands
 C:\>python -m pip install --upgrade pip
 C:\OSGEO4~1\bin\python.exe: No module named pip`

 3.2 Download get-pip.py to C:\OSGeo4W64, run with python.
 3.3 Try pip install qtconsole, answer from the shell:

`C:\OSGeo4W64>pip install qtconsole
Collecting qtconsole
C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:339
: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name I
ndication) extension to TLS is not available on this platform. This may cause th
e server to present an incorrect TLS certificate, which can cause validation fai
lures. You can upgrade to a newer version of Python to solve this. For more info
rmation, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-wa
rnings
  SNIMissingWarning
C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137
: InsecurePlatformWarning: A true SSLContext object is not available. This preve
nts urllib3 from configuring SSL appropriately and may cause certain SSL connect
ions to fail. You can upgrade to a newer version of Python to solve this. For mo
re information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html
#ssl-warnings
  InsecurePlatformWarning
  Downloading qtconsole-4.3.1-py2.py3-none-any.whl (108kB)
    100% |################################| 112kB 682kB/s
Collecting jupyter-core (from qtconsole)
  Downloading jupyter_core-4.4.0-py2.py3-none-any.whl (126kB)
    100% |################################| 133kB 853kB/s
Collecting jupyter-client>=4.1 (from qtconsole)
  Downloading jupyter_client-5.2.3-py2.py3-none-any.whl (89kB)
    100% |################################| 92kB 1.0MB/s
Collecting traitlets (from qtconsole)
  Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB)
    100% |################################| 81kB 910kB/s
Collecting ipython-genutils (from qtconsole)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting ipykernel>=4.1 (from qtconsole)
  Downloading ipykernel-4.8.2-py2-none-any.whl (108kB)
    100% |################################| 112kB 1.0MB/s
Collecting pygments (from qtconsole)
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
    100% |################################| 849kB 602kB/s
Requirement already satisfied: python-dateutil>=2.1 in c:\osgeo4~1\apps\python27
\lib\site-packages (from jupyter-client>=4.1->qtconsole)
Collecting pyzmq>=13 (from jupyter-client>=4.1->qtconsole)
  Downloading pyzmq-17.0.0-cp27-cp27m-win_amd64.whl (580kB)
    100% |################################| 583kB 930kB/s
Collecting tornado>=4.1 (from jupyter-client>=4.1->qtconsole)
  Downloading tornado-5.0.1.tar.gz (504kB)
    100% |################################| 512kB 1.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\y1234\appdata\local\temp\pip-build-jfxyaq\tornado\setup.py"
, line 146, in <module>
        raise ImportError("Tornado requires an up-to-date SSL module. This means
 "
    ImportError: Tornado requires an up-to-date SSL module. This means Python 2.
7.9+ or 3.4+ (although some distributions have backported the necessary changes
to older versions).

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\y1234\ap
pdata\local\temp\pip-build-jfxyaq\tornado\

C:\OSGeo4W64>`

As we can see we have error "up-to-date SSL module".
I tried to make everything according to the instruction
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
But it hasn't helped. 
I tried to find solution and find this issue:
#563 new defect - Bundle Python version is outdated in OSGeo4w package
https://trac.osgeo.org/osgeo4w/ticket/563

I installed tornado but only version 4.5.2
After that I try to install qtconsole again and get error:
`C:\>pip install qtconsole
Collecting qtconsole
  Using cached qtconsole-4.3.1-py2.py3-none-any.whl
Collecting jupyter-core (from qtconsole)
  Using cached jupyter_core-4.4.0-py2.py3-none-any.whl
Collecting jupyter-client>=4.1 (from qtconsole)
  Using cached jupyter_client-5.2.3-py2.py3-none-any.whl
Collecting traitlets (from qtconsole)
  Using cached traitlets-4.3.2-py2.py3-none-any.whl
Collecting ipython-genutils (from qtconsole)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting ipykernel>=4.1 (from qtconsole)
  Using cached ipykernel-4.8.2-py2-none-any.whl
Collecting pygments (from qtconsole)
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.1 in c:\osgeo4~1\apps\python27
\lib\site-packages (from jupyter-client>=4.1->qtconsole)
Collecting pyzmq>=13 (from jupyter-client>=4.1->qtconsole)
  Using cached pyzmq-17.0.0-cp27-cp27m-win_amd64.whl
Requirement already satisfied: tornado>=4.1 in c:\osgeo4~1\apps\python27\lib\sit
e-packages (from jupyter-client>=4.1->qtconsole)
Collecting enum34; python_version == "2.7" (from traitlets->qtconsole)
C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:339
: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name I
ndication) extension to TLS is not available on this platform. This may cause th
e server to present an incorrect TLS certificate, which can cause validation fai
lures. You can upgrade to a newer version of Python to solve this. For more info
rmation, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-wa
rnings
  SNIMissingWarning
C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\urllib3\util\ssl_.py:137
: InsecurePlatformWarning: A true SSLContext object is not available. This preve
nts urllib3 from configuring SSL appropriately and may cause certain SSL connect
ions to fail. You can upgrade to a newer version of Python to solve this. For mo
re information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html
#ssl-warnings
  InsecurePlatformWarning
  Downloading enum34-1.1.6-py2-none-any.whl
Requirement already satisfied: six in c:\osgeo4~1\apps\python27\lib\site-package
s (from traitlets->qtconsole)
Collecting decorator (from traitlets->qtconsole)
  Downloading decorator-4.2.1-py2.py3-none-any.whl
Collecting ipython>=4.0.0 (from ipykernel>=4.1->qtconsole)
  Downloading ipython-5.6.0-py2-none-any.whl (760kB)
    100% |################################| 768kB 598kB/s
Requirement already satisfied: certifi in c:\osgeo4~1\apps\python27\lib\site-pac
kages (from tornado>=4.1->jupyter-client>=4.1->qtconsole)
Requirement already satisfied: singledispatch in c:\osgeo4~1\apps\python27\lib\s
ite-packages (from tornado>=4.1->jupyter-client>=4.1->qtconsole)
Requirement already satisfied: backports.ssl-match-hostname in c:\osgeo4~1\apps\
python27\lib\site-packages (from tornado>=4.1->jupyter-client>=4.1->qtconsole)
Requirement already satisfied: backports-abc>=0.4 in c:\osgeo4~1\apps\python27\l
ib\site-packages (from tornado>=4.1->jupyter-client>=4.1->qtconsole)
Collecting backports.shutil-get-terminal-size; python_version == "2.7" (from ipy
thon>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading backports.shutil_get_terminal_size-1.0.0-py2.py3-none-any.whl
Collecting setuptools>=18.5 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading setuptools-39.0.1-py2.py3-none-any.whl (569kB)
    100% |################################| 573kB 656kB/s
Collecting simplegeneric>0.8 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading simplegeneric-0.8.1.zip
Collecting pickleshare (from ipython>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pathlib2; python_version == "2.7" or python_version == "3.3" (from ip
ython>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading pathlib2-2.3.0-py2.py3-none-any.whl
Collecting win-unicode-console>=0.5; sys_platform == "win32" and python_version
< "3.6" (from ipython>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading win_unicode_console-0.5.zip
Collecting colorama; sys_platform == "win32" (from ipython>=4.0.0->ipykernel>=4.
1->qtconsole)
  Downloading colorama-0.3.9-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython>=4.0.0->ipykernel>=4.1->qt
console)
  Downloading prompt_toolkit-1.0.15-py2-none-any.whl (247kB)
    100% |################################| 256kB 819kB/s
Collecting scandir; python_version < "3.5" (from pathlib2; python_version == "2.
7" or python_version == "3.3"->ipython>=4.0.0->ipykernel>=4.1->qtconsole)
  Downloading scandir-1.7-cp27-cp27m-win_amd64.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel
>=4.1->qtconsole)
  Downloading wcwidth-0.1.7-py2.py3-none-any.whl
Building wheels for collected packages: simplegeneric, win-unicode-console
  Running setup.py bdist_wheel for simplegeneric ... done
  Stored in directory: C:\Users\Y1234\AppData\Local\pip\Cache\wheels\7b\31\08\c8
5e74c84188cbec6a6827beec4d640f2bd78ae003dc1ec09d
  Running setup.py bdist_wheel for win-unicode-console ... done
  Stored in directory: C:\Users\Y1234\AppData\Local\pip\Cache\wheels\ff\91\6b\e2
83a7ffda03aaa6caa95849145d5c54a105917fae3ec3f54a
Successfully built simplegeneric win-unicode-console
Installing collected packages: enum34, ipython-genutils, decorator, traitlets, j
upyter-core, pyzmq, jupyter-client, backports.shutil-get-terminal-size, pygments
, setuptools, simplegeneric, scandir, pathlib2, pickleshare, win-unicode-console
, colorama, wcwidth, prompt-toolkit, ipython, ipykernel, qtconsole
  Found existing installation: setuptools 0.9.8
    Uninstalling setuptools-0.9.8:
      Successfully uninstalled setuptools-0.9.8
Successfully installed backports.shutil-get-terminal-size-1.0.0 colorama-0.3.9 d
ecorator-4.2.1 enum34-1.1.6 ipykernel-4.8.2 ipython-5.6.0 ipython-genutils-0.2.0
 jupyter-client-5.2.3 jupyter-core-4.4.0 pathlib2-2.3.0 pickleshare-0.7.4 prompt
-toolkit-1.0.15 pygments-2.2.0 pyzmq-17.0.0 qtconsole-4.3.1 scandir-1.7 setuptoo
ls-39.0.1 simplegeneric-0.8.1 traitlets-4.3.2 wcwidth-0.1.7 win-unicode-console-
0.5
Traceback (most recent call last):
  File "C:\OSGEO4~1\apps\Python27\lib\runpy.py", line 162, in _run_module_as_mai
n
    "__main__", fname, loader, pkg_name)
  File "C:\OSGEO4~1\apps\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\OSGEO4~1\apps\Python27\Scripts\pip.exe\__main__.py", line 9, in <modu
le>
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\__init__.py", line 248,
in main
    return command.main(cmd_args)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\basecommand.py", line 25
2, in main
    pip_version_check(session)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\utils\outdated.py", line
 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\utils\__init__.py", line
 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 644, in __init__
    self.add_entry(entry)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\pip\_vendor\pkg_resources\__
init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
WindowsError: [Error 2] : 'C:\\OSGEO4~1\\apps\\Python27\\lib\\site-packages\\set
uptools-0.9.8-py2.7.egg'

C:\>
`
But you can see qtconsole was install:

`C:\>pip show qtconsole
Name: qtconsole
Version: 4.3.1
Summary: Jupyter Qt console
Home-page: http://jupyter.org
Author: Jupyter Development Team
Author-email: jupyter@googlegroups.com
License: BSD
Location: c:\osgeo4~1\apps\python27\lib\site-packages
Requires: jupyter-core, jupyter-client, traitlets, ipython-genutils, ipykernel,
pygments

C:\>`

4. Item "Using PyCharm:"
Try to run frmMainEPANET.py

`C:\OSGeo4W64\bin\python.exe C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py
Traceback (most recent call last):
  File "C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 3, in <module>
    import sip
ImportError: No module named sip
Process finished with exit code 1`

I could not install sip from shell and PyCharm.
I install it from Setup OsGeo4W. From libs, SIP (ver 4.14.7-1).
After that I received:

`C:\OSGeo4W64\bin\python.exe C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py
Traceback (most recent call last):
  File "C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 8, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: No module named PyQt4
Process finished with exit code 1`

I install it from Setup OsGeo4W. From libs, pyqt4 (ver 4.10.2-1).
After that I recived:

`After that I recived:
C:\OSGeo4W64\bin\python.exe C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py
Traceback (most recent call last):
  File "C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 15, in <module>
    from ui.frmMain import frmMain, ModelLayers
  File "C:\Users\Y1234\PycharmProjects\SWMM-EPANET_User_Interface\src\ui\frmMain.py", line 12, in <module>
    from PyQt4.Qsci import QsciScintilla
ImportError: No module named Qsci
Process finished with exit code 1
`
I installed it from Setup OsGeo4W. From libs, qscintilla  (ver 2.7.2-1)
After that I received:
`C:\OSGeo4W64\bin\python.exe C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py
Traceback (most recent call last):
  File "C:/Users/Y1234/PycharmProjects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 15, in <module>
    from ui.frmMain import frmMain, ModelLayers
  File "C:\Users\Y1234\PycharmProjects\SWMM-EPANET_User_Interface\src\ui\frmMain.py", line 30, in <module>
    from ui.frmTranslateCoordinates import frmTranslateCoordinates
  File "C:\Users\Y1234\PycharmProjects\SWMM-EPANET_User_Interface\src\ui\frmTranslateCoordinates.py", line 7, in <module>
    from ui.selectCrsDlg import SelectCrsDlg
  File "C:\Users\Y1234\PycharmProjects\SWMM-EPANET_User_Interface\src\ui\selectCrsDlg.py", line 24, in <module>
    from qgis.gui import QgsProjectionSelector
  File "C:\OSGeo4W64\apps\qgis\python\qgis\__init__.py", line 26, in <module>
    from builtins import zip
ImportError: No module named builtins
Process finished with exit code 1`

Can't solve this...

Dear colleagues, please help.
Maybe I made a mistake somewhere?

**Comment by Yust11135** [comment]
I have reinstalled
-windows 7 pro
-OSGeo4W64
-python 2.7.14 (https://trac.osgeo.org/osgeo4w/wiki/pkg-python/Python27#no1)

`C:\OSGeo4W64\bin\python.exe C:/Projects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py
Traceback (most recent call last):
  File "C:/Projects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 16, in <module>
    from ui.frmMain import frmMain, ModelLayers
  File "C:\Projects\SWMM-EPANET_User_Interface\src\ui\frmMain.py", line 30, in <module>
    from ui.frmTranslateCoordinates import frmTranslateCoordinates
  File "C:\Projects\SWMM-EPANET_User_Interface\src\ui\frmTranslateCoordinates.py", line 7, in <module>
    from ui.selectCrsDlg import SelectCrsDlg
  File "C:\Projects\SWMM-EPANET_User_Interface\src\ui\selectCrsDlg.py", line 24, in <module>
    from qgis.gui import QgsProjectionSelector
  File "C:\OSGeo4W64\apps\qgis\python\qgis\__init__.py", line 71, in <module>
    from qgis.PyQt import QtCore
  File "C:\OSGeo4W64\apps\qgis\python\qgis\PyQt\QtCore.py", line 26, in <module>
    from PyQt5.QtCore import *
ImportError: No module named PyQt5.QtCore

Process finished with exit code 1`

Please help.

**Comment by accumodel** [comment]
I have often wondered why it was decided to build the UI using QGIS building blocks rather than as a plugin.  Does anyone know?  Did going with plugin style not provide enough functionality?  Having not yet created a plugin for QGIS, obviously I am oblivious to the complexities.

**Comment by Yust11135** [comment]
@michaeltryby Thanks for the explanation, I agree that GUI must be friendly and usable for all users, first of all for users with little experience of calculating systems, but with a great desire to do their work with the program is good. I'm sure that the new version of the program can help. I see an excellent perspective to make the program modern and useful. And that's why I go to learn Python.
By the nature of its activities, I need to consider the ramified hydraulic networks. I have a little experience with EPANET 2.0 (about three years) and about half a year I adapted (as far as I could remember Pascal) GUI EPANET 2.0 for my tasks. I realized that I do not have enough programming knowledge and decided to go to study. I choose for a long time - go to Pascal courses, which would be a more straightforward task, or go to study Python with from the basics.
It is a difficult choice because it is not the primary job and I only have 2 hours a day to do something.
I decided to study Python because of new interface based on the great principles. I have a firm belief that I can learn, which is why I try to run the program again and again.
Thanks for the support.

**Comment by Yust11135** [comment]
@samhatchett Thanks for the support.
I add the paths:
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis\python;%PYTHONPATH%
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\bin
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\bin\arch
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\qgis
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\qgis\bin
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\qgis\python
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python27
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python27\Scripts
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python27\Lib
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python27\Lib\site-packages
SET PYTHONPATH=%PYTHONPATH%;%OSGEO4W_ROOT%\apps\Python27\DLLs
SET QGIS_PREFIX_PATH=%OSGEO4W_ROOT%\apps\qgis

Now if I run frmMainEpanet.py (Shift+F10) then I have:
`Traceback (most recent call last):
  File "C:/Projects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 18, in <module>
    from ui.frmMain import frmMain, ModelLayers
  File "C:\Projects\SWMM-EPANET_User_Interface\src\ui\frmMain.py", line 30, in <module>
    from ui.frmTranslateCoordinates import frmTranslateCoordinates
  File "C:\Projects\SWMM-EPANET_User_Interface\src\ui\frmTranslateCoordinates.py", line 7, in <module>
    from ui.selectCrsDlg import SelectCrsDlg
  File "C:\Projects\SWMM-EPANET_User_Interface\src\ui\selectCrsDlg.py", line 24, in <module>
    from qgis.gui import QgsProjectionSelector
  File "C:\OSGEO4~1\apps\qgis\python\qgis\__init__.py", line 71, in <module>
    from qgis.PyQt import QtCore
  File "C:\OSGEO4~1\apps\qgis\python\qgis\PyQt\QtCore.py", line 26, in <module>
    from PyQt5.QtCore import *
ImportError: DLL load failed: The specified module could not be found.`

If I debug frmMainEpanet.py (Shift + F9) then I have:

`Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1664, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\helpers\pydev\pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Projects/SWMM-EPANET_User_Interface/src/ui/EPANET/frmMainEPANET.py", line 11, in <module>
    from PyQt4 import QtGui, QtCore
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1`

Why in one case I get an error with PyQt4 and in the other case with PyQt5?
What can I do with Dll? How to specify the path to them?
How to check which Dlls are needed?

Thanks for any help.

**Comment by Yust11135** [comment]
Dear colleagues, 

Link:
[Updated python to 2.7.14 as experimental in x86 and x86_64 (pip.exe should now work)](https://trac.osgeo.org/osgeo4w/ticket/567#comment:8)

**In part of "Getting Started as a Developer" Install QGIS
item 7, we must select the latest version of:**
python-core 2.7.14-1
python-tools 2.7.14-1
python-tcltk 2.7.14-1
setup 1.0.7-16
shell 1.0.2-2
**qgis-ltr-full** 2.18-1 (because it connected with PyQt4)
gdal-filegdb 2.2.4-1
python-devel 2.7.14-1
setuptools 39.2.0-1

Now pip work.

But if I started with OSGeo4W Shell and try **import qgis** I get an error.
I found a solution in python-qgis-ltr.bat (in C:\OSGeo4W64\bin):
In folder C:\OSGeo4W64 right click on the OSGeo4W.bat file -> Edit
replace content to:

_@echo off
call "C:\OSGeo4W64\bin\o4w_env.bat"
@echo off
path %OSGEO4W_ROOT%\apps\qgis-ltr\bin;%PATH%
set QGIS_PREFIX_PATH=%OSGEO4W_ROOT:\=/%/apps/qgis-ltr
set GDAL_FILENAME_IS_UTF8=YES
rem Set VSI cache to be used as buffer, see #6448
set VSI_CACHE=TRUE
set VSI_CACHE_SIZE=1000000
set QT_PLUGIN_PATH=%OSGEO4W_ROOT%\apps\qgis-ltr\qtplugins;%OSGEO4W_ROOT%\apps\qt4\plugins
set PYTHONPATH=%OSGEO4W_ROOT%\apps\qgis-ltr\python;%PYTHONPATH%
rem List available o4w programs
rem but only if osgeo4w called without parameters
@echo on
@if [%1]==[] (echo run o-help for a list of available commands & cmd.exe /k) else (cmd /c "%*")_

Now you can import qgis. 
I understand that there is a problem with indicating the paths, but I could not solve it by changing the environment, I changed  OSGeo4W.bat file. Because of this, you have to run PyCharm through the bat file by adding the line at the end of the bat file:

@"C:\Program Files\JetBrains\PyCharm Community Edition 2018.1.2\bin\pycharm64.exe"

You should check the version of the PyCharm program that you have installed and correct number correspondingly.

Colleagues, please check my suggestions. Might someone can give advice
 how to change the virtual environment that there was no need to run PyCharm through the bat file.

Thanks.

**Comment by PaulDudaRESPEC** [comment]
See new instructions added for Python 3 version
