### ISSUE TITLE
project is missing file frmOptionsDesigner.ui

### ISSUE THREAD

**Issue by samhatchett** [USEPA/SWMM-EPANET_User_Interface#250]
the auto-generated file `src/ui/frmOptionsDesigner.py` is missing the origin `ui` file

https://github.com/USEPA/SWMM-EPANET_User_Interface/blob/14d96df3690439eba7cc4a27a2cae24be1980e4a/src/ui/frmOptionsDesigner.py#L3

**Comment by PaulDudaRESPEC** [comment]
Looks like there may be other .ui files missing in addition to this one.

**Comment by TongZhai** [comment]
@samhatchett it is checked in.
