### ISSUE TITLE
ENsetnodevalue sets zero value (passing a reference rather than value)

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#255]
ENsetnodevalue sets zero value (passing a reference rather than value)

Version: EPANET MTP4r2 (master branch)
Priority: High

**Comment by TongZhai** [comment]
@ehsanMa86 need more details

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
