### ISSUE TITLE
Having an space at the name of folder on plugin environment doesn't load them from the UI

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#257]
Having an space at the name of folder on plugin environment doesn't load them from the UI

Version: EPANET MTP4r2 (master branch)
Priority: Low

**Comment by TongZhai** [comment]
@ehsanMa86 The plugin folder name can have space, the key is to ensure the `plugin_name` variable is set to the same folder name (including space) in the `__init__.py` file inside the plugin folder.
