### ISSUE TITLE
When displaying thematic map of model results, show current time.

### ISSUE THREAD

**Issue by MarkGrayRESPEC** [USEPA/SWMM-EPANET_User_Interface#26]
The start and end time are both displayed on the control for changing the time, but the current time is not yet shown.

**Comment by TongZhai** [comment]
current time display is added to the time control ([d1a531cf90c193f94e23ba978403d0a657ce9e43](https://github.com/USEPA/SWMM-EPANET_User_Interface/commit/d1a531cf90c193f94e23ba978403d0a657ce9e43)); it is working in EPANET, but not in SWMM as the animation capability is not yet implemented in SWMM.

**Comment by PaulDudaRESPEC** [comment]
This issue is resolved.
