### ISSUE TITLE
Program crashes activating Maps and Layers

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#260]
Program crashes activating Maps and Layers

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by TongZhai** [comment]
@ehsanMa86 need more details as we cannot reproduce the crash while manipulating the layers on map

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
