### ISSUE TITLE
GDAL_DATA environment variable to point to the directory containing EPSG csv files

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#262]
GDAL_DATA environment variable to point to the directory containing EPSG csv files

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by TongZhai** [comment]
@ehsanMa86 The python 3 development environment is much easier to setup, please follow the Wiki instruction entitled: Getting Started as a Developer in Python 3
