### ISSUE TITLE
qtconsol installation is out of date

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#264]
qtconsol installation is out of date

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by TongZhai** [comment]
@ehsanMa86 need more details

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
