### ISSUE TITLE
Curve points are limited to 48 and if the user upload more points, it will be redundant.

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#266]
Curve points are limited to 48 and if the user upload more points, it will be redundant.

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by PaulDudaRESPEC** [comment]
I built an example with 50 points on a curve, and it read in without a problem.  Maybe the user could supply more details and an example?

**Comment by TongZhai** [comment]
@ehsanMa86 the fix above will allow uploading and saving of curve with arbitrary number of points, also the graphing is improved to be more efficient during loading process
