### ISSUE TITLE
Minimizing the project window loses the working windows and it is impossible to return it back

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#267]
Minimizing the project window loses the working windows and it is impossible to return it back

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by TongZhai** [comment]
@ehsanMa86 One can bring back Project Explorer, Object Explorer, as well as any of the 3 main toolbars by right-mouse-click anywhere on the menu bar at the top of the UI.
