### ISSUE TITLE
INP saved when model is ran

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#27]
After making changes to the model and clicking the run button the INP file is being saved without any prompt. I think it should be allowed to run the model without saving changes.

**Comment by MarkGrayRESPEC** [comment]
In the existing production version, the input file is quietly saved to a temporary folder where the model is run. In the current MTP, the input file is saved in place where it was opened from and is run in that folder, producing all output files there. This is a change that warrants further discussion. I find the new behavior more in line with software development tools that save the source code in place before compiling and running, but this workflow could be changed to be more like it used to be.

**Comment by eladsal** [comment]
I find the current EPANET way to be appropriate. However, if you are going to save the INP the least you can do is alert the user, he might want to save it in a different name.
