### ISSUE TITLE
Using zero time step in steady state solution crashes the summary report

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#273]
Using zero time step in steady state solution crashes the summary report

Version: EPANET MTP4r2 (master branch)
Priority: High

**Comment by TongZhai** [comment]
@ehsanMa86 We could not reproduce this error. Please provide more details and the input file you used for this failed test.

**Comment by TongZhai** [comment]
@ehsanMa86 with the above commit, it will be easier to set up steady state simulation.
