### ISSUE TITLE
Zooming in or out puts all the elements on together and doesn't zoom back to the same level of visibility

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#275]
Zooming in or out puts all the elements on together and doesn't zoom back to the same level of visibility

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
