### ISSUE TITLE
making the executable file for windows fails the procedure for both SWMM and EPANET

### ISSUE THREAD

**Issue by ehsanMa86** [USEPA/SWMM-EPANET_User_Interface#277]
making the executable file for windows fails the procedure for both SWMM and EPANET

Version: EPANET MTP4r2 (master branch)
Priority: Medium

**Comment by dickinsonre** [comment]
I get this message when i try to install 
![2019-03-08_1448](https://user-images.githubusercontent.com/5599939/54052143-aa148880-41b1-11e9-9c73-20d5584e752f.png)

**Comment by TongZhai** [comment]
@dickinsonre we have been moving everything to python3 for quite a while now, could you try the MTP5r0 python 3 install package, see if it resolve this install problem.

**Comment by schoeller** [comment]
@TongZhai I can confirm the message from @dickinsonre when installing on Win10 using the MTPr0 for SWMM.

![Neues Bild](https://user-images.githubusercontent.com/106036/54065980-14641200-4220-11e9-88c7-7d531aa52e74.jpg)

**Comment by dickinsonre** [comment]
I have now tried it on three PC's and all give the same error.  I am using SWMM-UI-MTP5r0.exe and get the same error as mentioned by @TongZhai

**Comment by TongZhai** [comment]
@dickinsonre yes, there is a problem on win10, I am looking at this, had some success, will need more testing before an update.

**Comment by TongZhai** [comment]
@schoeller @dickinsonre
new windows 10 installers are released at the [release page](https://github.com/USEPA/SWMM-EPANET_User_Interface/releases/tag/MTP5r0), please try.

**Comment by dickinsonre** [comment]
Thanks both of these installs work for me and run but  SWMM is still using the v11 engine

  EPA STORM WATER MANAGEMENT MODEL - VERSION 5.1 (Build 5.1.011)

**Comment by ehsanMa86** [comment]
@TongZhai May I ask what changes you made on the process to make install packages for Windows 10? Just curious

**Comment by schoeller** [comment]
> 
> 
> @schoeller @dickinsonre
> new windows 10 installers are released at the [release page](https://github.com/USEPA/SWMM-EPANET_User_Interface/releases/tag/MTP5r0), please try.

@TongZhai 
Thx for the work. I tried and both installers quit successfully. When trying to launch EPANET-UI.exe though I receive the following error
![image](https://user-images.githubusercontent.com/106036/54339938-2681ee00-462e-11e9-88c2-2c962a614ba8.png)
SWMM-UI.exe behaves similar. I suspect this originating from that I have not installed QGis through OSGeo4W network installer as suggested on https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Getting-Started-as-a-Developer-in-Python-3. I rather have a standard QGis install.

**Comment by TongZhai** [comment]
@schoeller I see it. It does seem it still needs something from the installed qgis folder... I tested the dependency on qgis by renaming, deleting, and moving the installed qgis folder and the programs still worked. I think I can see a path forward to resolve this, so I am reopening this thread, will post update soon.
