### ISSUE TITLE
EPANET crashes after graph image is saved to png file

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#28]
After a figure is plotted and saved as a PNG file the program crashes (on Win 8.1)
![screenshot 280](https://cloud.githubusercontent.com/assets/1942312/21384107/a28438de-c771-11e6-9ab2-de90f3b4d9d6.png)

**Comment by eladsal** [comment]
No I see that the exported PNG file is empty and could not be opened.

**Comment by MarkGrayRESPEC** [comment]
A fix has not yet been found, but this has been traced to line 677 of 
Python27\Lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg\matplotlib\backends\backend_qt4.py

                self.canvas.print_figure( unicode(fname) )

This is inside a try statement, but the crash is not able to be caught by Python exception handling.

**Comment by MarkGrayRESPEC** [comment]
This looks like an issue others have had with matplotlib, no solution found yet but some more information:
https://trac.osgeo.org/osgeo4w/ticket/451
https://hub.qgis.org/issues/13982

**Comment by PaulDudaRESPEC** [comment]
Seems the Python3 version of matplotlib fixes this issue
