### ISSUE TITLE
default label placement on map

### ISSUE THREAD

**Issue by jlkittle** [USEPA/SWMM-EPANET_User_Interface#284]
maptools.py line 786 ->           pal_layer.placement = QgsPalLayerSettings.AboveLine

causes a type mismatch on linux, suggest a change to 

pal_layer.placement = QgsPalLayerSettings.AroundPoint

**Comment by TongZhai** [comment]
@jlkittle AboveLine is the choice for line features and it is equally valid as the AroundPoint enum in pyqgis 3. So, if it complains about one, it should complain about the other... were you able to run it or would it fail there?

**Comment by PaulDudaRESPEC** [comment]
Changing this one to 'needs more info' for now, while awaiting testing on Linux.

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
