### ISSUE TITLE
detect if model has been changed after open or save

### ISSUE THREAD

**Issue by TongZhai** [USEPA/SWMM-EPANET_User_Interface#286]
Mechanism for detecting changes made to a model after loaded into the UI or after a recent 'Save'. Right now, changes will be thrown away if users don't save a copy via either 'Save' or 'Save As'. Also, detecting if model is changed, could also help direct event such as clearing the status report from a previous run.

**Comment by PaulDudaRESPEC** [comment]
Fixed.  Each UI element that makes changes to the core has been tested to ensure it properly triggers the 'unsaved changes' warning.
