### ISSUE TITLE
Unicode Issue

### ISSUE THREAD

**Issue by MatiasSeoane** [USEPA/SWMM-EPANET_User_Interface#288]
I get the next message when i try to run a model (it worked fine in other cases):

'ascii' codec can't encode character u'\xe9' in position 20: ordinal not in range(128)

I've checked my inp file and there are no latin characters or anything like that.

**Comment by Skulldron** [comment]
Check if file path contains any strange characters

**Comment by michaeltryby** [comment]
@MatiasSeoane we kindly request that you attach the input file to the Issue so we may investigate. Thank you!

**Comment by michelleannesimon** [comment]
Still needs more documentation to resolve this comment.

**Comment by michelleannesimon** [comment]
Does support request mean that we need more information to understand the issue?

**Comment by dickinsonre** [comment]
I don't know if that helps but I often get a odd input file for SWMM5 and have to resave it from Excel in a plain MSDOS format.  This is especially a common problem with SWMM5 calibration files.

**Comment by MatiasSeoane** [comment]
I've already checked that before there are no strange characters, inp file is in the next link:

https://drive.google.com/open?id=19nD05GyIiKUSOhH10ZCKSXypgWXQEd_v

**Comment by TongZhai** [comment]
@MatiasSeoane We are revisiting this issue. If you can provide the input file again, as the input file link is not working anymore. Anyway, this has to do with the codec used for writing and reading an input file, I think python default is ascii codec that can't handle unicode, there might be some places in the input file reader/writer that need to use proper encoder, your example input file should help finding those.

**Comment by TongZhai** [comment]
The fix allows special latin1 characters (some perhaps), also still catch bad file such as binary file as input.
