### ISSUE TITLE
System flow balance plot is wrong

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#29]
The EPANET System flow balance plot is wrong. See for Net1:
![screenshot 281](https://cloud.githubusercontent.com/assets/1942312/21384870/f45bf8d8-c774-11e6-876d-9d686982f02b.png)

Should be:
![screenshot 283](https://cloud.githubusercontent.com/assets/1942312/21384906/11bd5e12-c775-11e6-9803-540092c2b178.png)

**Comment by TongZhai** [comment]
Could you please provide the graphing choices you used to generate your graphs so we can try to replicate this issue?

**Comment by eladsal** [comment]
These settings:
![screenshot 320](https://cloud.githubusercontent.com/assets/1942312/26436221/ac3d8382-411d-11e7-9f02-7d15bc5e2fef.png)
