### ISSUE TITLE
Migrate code base to QGIS 3.4

### ISSUE THREAD

**Issue by TongZhai** [USEPA/SWMM-EPANET_User_Interface#291]
Migrate code base to first QGIS LRT 3.4 to deal with a host of issues including packaging. The packaging of an abbreviated test qgis application succeeded with this LRT version.

**Comment by TongZhai** [comment]
The last test qgis application package development using the QGIS 3.4.2 was successful before the government shutdown (end of January, 2019). The QGIS 3.4.2 version has Qt5 libraries' paths set to outside of the usual C:\OSGeo4W64 install directory. Effort resumed after the shutdown. QGIS long term release version 3.4.4 was installed and the qgis test package failed again due to further pyqt5 supporting library (such as QtPrintSupport, QtSql, QtNetwork etc) problem. Due to the fact that osgeo installer dynamically download latest libraries from repos, we cannot go back to QGIS 3.4.2 either. So, at the moment, we are trying to report this issue to the official qgis issue trac system. Anyone who already has the proper credential on QGIS trac system, can help post this issue. This is ongoing.

**Comment by TongZhai** [comment]
I was able to open a new issue on QGIS application issue tracker website per this issue, waiting for further response

**Comment by TongZhai** [comment]
I have updated development stack to the latest QGIS 3.6 'Noosa' version and have successfully built the first python 3 EPANET package that runs with map display. A bit more testing will follow and will advise team migration to this latest version.

**Comment by accumodel** [comment]
Thanks for the hard work all.

After installing I get two errors.  See screenshot below.  I installed Noosa and tried again with the same results.

![image](https://user-images.githubusercontent.com/13052801/54127188-381d8880-43d7-11e9-85e4-3c31a356df47.png)

![image](https://user-images.githubusercontent.com/13052801/54127213-49669500-43d7-11e9-961c-f2e67f02b012.png)

**Comment by TongZhai** [comment]
Yes, there is a problem on windows 10. I have been looking at this issue and had some limited success on windows 10, will need to test some more before releasing an update.

**Comment by TongZhai** [comment]
The new windows 10 installers were [released](https://github.com/USEPA/SWMM-EPANET_User_Interface/releases/tag/MTP5r0) and tested to run successfully, also closed issue #277
