### ISSUE TITLE
MTP5r - Simulate model - No module named 'pyepanet'

### ISSUE THREAD

**Issue by accumodel** [USEPA/SWMM-EPANET_User_Interface#292]
I installed the latest MTP5r and it opens great now on Windows 10.  Trying to simulate the model though, and get the following error:

![image](https://user-images.githubusercontent.com/13052801/54632678-a227d480-4a4c-11e9-8b3a-6755cc182fdb.png)

**Comment by TongZhai** [comment]
@accumodel the latest windows 10 version doesn't trigger this error when running a model.

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
