### ISSUE TITLE
Can't run MTP5r1

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#294]
I downloaded SWMM-UI-MTP5r1.exe and installed it on a Windows 10 machine.  When I try to run the SWMM-UI.exe, the console closes quickly; here is the output from the command prompt:

```
C:\Users\cbarr02\SWMM-UI>SWMM-UI.exe
Traceback (most recent call last):
  File "ui\SWMM\frmMainSWMM.py", line 15, in <module>
  File "c:\OSGEO4~1\apps\Python37\lib\site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "ui\frmMain.py", line 35, in <module>
  File "c:\OSGEO4~1\apps\Python37\lib\site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "ui\frmTranslateCoordinates.py", line 7, in <module>
  File "c:\OSGEO4~1\apps\Python37\lib\site-packages\pyinstaller-3.4-py3.7.egg\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "qgis\gui\__init__.py", line 27, in <module>
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.
[12676] Failed to execute script frmMainSWMM
```

**Comment by dickinsonre** [comment]
I concur with Colleen issues = the messages I get are the same.

**Comment by TongZhai** [comment]
Could you open a dos command console and do a dir under C:\ and post the directories here. Thanks.

**Comment by barrc** [comment]
```
C:\>dir
 Volume in drive C is OSDisk
 Volume Serial Number is 70D6-7D38

 Directory of C:\

07/01/2015  01:30 PM    <DIR>          HERO
08/10/2018  07:53 PM    <DIR>          inetpub
07/01/2015  10:36 AM    <DIR>          Intel
07/01/2015  01:31 PM               599 LitCiterInstallLog.txt
07/01/2015  01:28 PM    <DIR>          LitciterTemp
07/01/2015  01:06 PM    <DIR>          MININT
06/10/2019  01:42 PM    <DIR>          ORDTools
12/13/2017  06:41 PM    <DIR>          PerfLogs
05/22/2019  04:13 PM    <DIR>          Program Files
06/24/2019  08:39 AM    <DIR>          Program Files (x86)
04/01/2019  02:32 PM    <DIR>          Python27
07/19/2018  12:57 PM    <DIR>          Quarantine
06/24/2019  11:42 AM    <DIR>          src
04/23/2018  08:51 AM    <DIR>          Sun
06/24/2019  04:39 PM           259,696 SUService.log
09/22/2016  05:04 PM                 0 t2t8
05/31/2018  06:01 AM    <DIR>          temp
08/13/2018  05:20 PM    <DIR>          Users
06/24/2019  09:28 AM    <DIR>          Windows
               3 File(s)        260,295 bytes
              16 Dir(s)  43,540,107,264 bytes free
```

**Comment by ehsanMa86** [comment]
This message means some dlls are missing. There should be a _gui.dll file in qgis folder which is missing or corrupted.

**Comment by TongZhai** [comment]
@barrc please download qgis from this link and install on your windows 10 machine, then try to launch it again, see if it works.

http://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-3.6.0-1-Setup-x86_64.exe

**Comment by TongZhai** [comment]
@barrc install it to C:\OSGeo4W64 directory

**Comment by barrc** [comment]
@TongZhai that worked.

**Comment by TongZhai** [comment]
@barrc now, uninstall QGIS from your windows 10, see if still works.

**Comment by barrc** [comment]
@TongZhai it no longer works.  Fails with the same error as before.

**Comment by TongZhai** [comment]
@barrc ok, thanks for helping with debugging this. I've seen cases where installing QGIS then uninstalling it would make the program work, I guess it is not a sure thing. But I think it seems to indicate the packaging process still hasn't gotten everything with its dependency walker, I am going to chalk this up to some degree on QGIS with its custom way of compiling pyqt libraries into its qgis GUI libraries instead of using standard Qt installation. We will continue to seek out the missing piece, and installing the QGIS program would be stop gap measure for now. I will update the release note to include this point.

**Comment by TongZhai** [comment]
@barrc if not too much trouble, could you try install the latest QGIS program and see it still work? link below:

http://qgis.org/downloads/QGIS-OSGeo4W-3.8.0-1-Setup-x86_64.exe

**Comment by barrc** [comment]
@TongZhai sure.  I installed the version you linked to the C:\OSGeo4W64 directory and it ran successfully.

**Comment by TongZhai** [comment]
@barrc thanks. This might not be version dependent then, which is certainly a welcome sign.

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
