### ISSUE TITLE
Can not configure development environment to successfully run UI

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#296]
I followed the instructions found [here](https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Getting-Started-as-a-Developer-in-Python-3) to configure the development environment, but the UI fails to launch and Python crashes frequently. 

I haven't been able to gather much in the way of diagnostic information, however, I believe the problem may be related to Python2 and Python3 running in the same environment.

**Comment by PaulDudaRESPEC** [comment]
Hey Michael (@michaeltryby), you might try deleting the Python27 folder, or if that seems too risky, at least rename it temporarily (to something like Python27x for instance) so any environment variables pointing to it won't resolve.  Then open up PyCharm afresh, and hopefully things will proceed more successfully.  I ended up deleting Python27 entirely to get things working well in Python37.

**Comment by michelleannesimon** [comment]
Hi Tong,
Faryn and I are looking for the latest prerelease to test the gui.  We see the June prerelease but is there a later one?

**Comment by michaeltryby** [comment]
@TongZhai and @PaulDudaRESPEC I've made some progress on this issue. The attached batch file sets the necessary environment variables to run PyQGIS and then launches PyCharm. This should make it easier for developers to configure their local environment. 

[env_init.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/3503103/env_init.txt)

To run it change the extension to `.cmd` or `.bat` and then edit and set `OSGEO4W_ROOT` and `PYCHARM_PATH` corresponding to local install locations respectively. Save and double click to run. It works reliably on my machine.

**Comment by PaulDudaRESPEC** [comment]
Closing old issues, assuming this issue is not relevant to the current version of the software.  Feel free to re-open if the problem still occurs.
