### ISSUE TITLE
About section need the update for the version

### ISSUE THREAD

**Issue by Mariosmsk** [USEPA/SWMM-EPANET_User_Interface#298]
![image](https://user-images.githubusercontent.com/2945956/62368269-cc2def00-b534-11e9-8c79-a63e5d0dd2e1.png)

I use the MTP5r2 version!

**Comment by TongZhai** [comment]
@Mariosmsk Thanks for pointing out the about info discrepancy. This will be corrected in subsequent releases.

**Comment by TongZhai** [comment]
[MTP5r3](https://github.com/USEPA/SWMM-EPANET_User_Interface/releases/tag/MTP5r3) is released and the about info is updated.
