### ISSUE TITLE
cannot specify the infiltration method on the project defau;lt

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#303]
When I try to specify the infiltration method on the project default or adding a subcatchment.  I think that i can change it in the general options window. 

![image](https://user-images.githubusercontent.com/26123284/64549458-b7e0cd00-d2fe-11e9-8e3d-6fb151c24617.png)

**Comment by michelleannesimon** [comment]
See issue #237.

**Comment by PaulDudaRESPEC** [comment]
I was able to reproduce the issue in MTP5R3, where the button to set the default infiltration was not working (it was related to the upgrade from Python 2 to Python 3).  Its now fixed, and the fix will be included in the next MTP installer.  The flow units combo box (referenced above in #237) has been fixed as well.

**Comment by michelleannesimon** [comment]
While the Infiltration Model is still grayed out, we can get to the different infiltration methods:
![image](https://user-images.githubusercontent.com/26123284/65267443-ffc3d900-dae2-11e9-9401-9b68358080e4.png)

**Comment by michelleannesimon** [comment]
A couple of the infiltration screens are missing explanatory notes:
![image](https://user-images.githubusercontent.com/26123284/65267511-2255f200-dae3-11e9-9c81-b068da6cb4f7.png)

This should look like:
![image](https://user-images.githubusercontent.com/26123284/65267545-3ac60c80-dae3-11e9-8332-79553f8deb0a.png)

**Comment by PaulDudaRESPEC** [comment]
I see the explanatory note for each property as I click on it.
