### ISSUE TITLE
Program is often unstable 

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#304]
When I try to change the infiltration method on the Project Default screen or change flow units to LPS, the project crashes:

![image](https://user-images.githubusercontent.com/26123284/64549617-0f7f3880-d2ff-11e9-9fab-a66f6eb213ba.png)

**Comment by michelleannesimon** [comment]
It continues to crash when I adjust properties of the dynamic wave, add a time series,

**Comment by PaulDudaRESPEC** [comment]
I was able to reproduce the issue in MTP5R3, where the button to set the default infiltration was not working (it was related to the upgrade from Python 2 to Python 3). Its now fixed, and the fix will be included in the next MTP installer. The flow units combo box (referenced above in #237) has been fixed as well.  We will continue to look for the other sources of instability.

**Comment by PaulDudaRESPEC** [comment]
The 'View' button from the time series editor does not work -- it appears to be something related to the conversion from Python 2 to Python 3.  We'll dig into it.

**Comment by PaulDudaRESPEC** [comment]
Fixed
