### ISSUE TITLE
Program slowly opens and sometimes double opens.

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#309]
It takes a while to get the GUI to pen and I get this screen:

![image](https://user-images.githubusercontent.com/26123284/64554022-91c02a80-d308-11e9-8fbd-24853000f941.png)
It usually double opens.

**Comment by michelleannesimon** [comment]
Version MTP5r5 seems to load faster and only opens one copy.

**Comment by TongZhai** [comment]
@michelleannesimon after your computer upgrade, have you tried out the latest release, is this still an issue?

**Comment by PaulDudaRESPEC** [comment]
Michelle indicates this is better now.
