### ISSUE TITLE
Make Default Node Geometry Window bigger so that labels are legible

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#311]
![image](https://user-images.githubusercontent.com/26123284/65268157-90e77f80-dae4-11e9-8459-969ea6aa2e4c.png)

Also check default values for each shape.

**Comment by michelleannesimon** [comment]
Many of my editor windows are not completely projected.  Is it an issue with my screen resolution.

**Comment by michelleannesimon** [comment]
I cannot see a clear picture of my dates and times, even when I adjust the screen size.
![image](https://user-images.githubusercontent.com/26123284/73489504-b2048a80-4378-11ea-829e-bcb4fb51a2cd.png)

**Comment by michelleannesimon** [comment]
Which is far different from Colleen's
![image](https://user-images.githubusercontent.com/26123284/73491008-ad8da100-437b-11ea-97f5-34c3bb9dd509.png)

**Comment by michelleannesimon** [comment]
Click onto it but if you click on it if will get larger

**Comment by barrc** [comment]
I think this can be closed with #355, Paul's work to make the default dates form larger, and #405.
