### ISSUE TITLE
Trying to add Subcatchment caused program to lock up

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#313]
The program just stopped - it did not save.  I tried to "end task" in Task Manager but even Task Manager froze.  After about 5 min, I got this screen.  

![image](https://user-images.githubusercontent.com/26123284/65270746-cb075000-dae9-11e9-9498-fdb73a1ec11d.png)

A

**Comment by PaulDudaRESPEC** [comment]
Appears related to setting infiltration parameters, which is fixed in the next MTP.

**Comment by michelleannesimon** [comment]
Problem persists in SWMM-UI-MTP6r0.exe

**Comment by TongZhai** [comment]
@michelleannesimon  Just tried this on our new testing machine with windows 10, I was able to add subcatchment in a blank project, and add subcatchment in existing projects, save etc without issue... Could you outline the steps you took to arrive at this failure on your system?

**Comment by PaulDudaRESPEC** [comment]
I think this problem might be related to specifying an invalid subcatchment outlet.  I recently checked in an enhancement that makes the subcatchment outlet field a drop-down list so that only valid outlets can be specified -- I think this will prevent this error in the future.

**Comment by PaulDudaRESPEC** [comment]
Added drop-down list of outlets as described above, seems to fix this issue (MTP6r1)
