### ISSUE TITLE
Adding LID Controls does not increase number

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#314]
Adding more LIDs does not increase the number.  You cannot change the name of a LID after it has been listed under the LID Controls Table but you can for rain gages, nodes, and conduits.

**Comment by PaulDudaRESPEC** [comment]
Fixed in the upcoming MTP

**Comment by PaulDudaRESPEC** [comment]
Fixed in MTP6r1
