### ISSUE TITLE
MTP6r0 Simulation Hangs

### ISSUE THREAD

**Issue by accumodel** [USEPA/SWMM-EPANET_User_Interface#318]
Installed suggested QGIS and then MTP6r0.  Open Net1 file.  Click simulation button.  Program hangs without finishing simulation.  No feedback on problem in log window.

Environment: Windows 10 Enterprise

**Comment by dickinsonre** [comment]
now that you mention it, Mark.  The same happens to me with the new installs for EPANET and SWMM.

**Comment by dickinsonre** [comment]
I did have a few past versions of the RESPEC installed programs on my PC so I uninstalled them all and then reinstalled the current SWMM GUI.  It still does not work - I get a blank screen and then it exits.

**Comment by TongZhai** [comment]
ok, so it doesn't seem to have to do with model engine. After you uninstall other versions, then reinstall the latest MTP6r0, do you have QGIS program installed to C:\OSGeo4W64\ directory? if not, try install QGIS to that directory, then try launch the program again.

**Comment by dickinsonre** [comment]
I wanted to mention that on a new PC without QGIS and Python I was finally able to install both EPANET and SWMM5 and get it to run and graph for many models.  I still cannot do this on my other two PC's but maybe they have too many other Softwares on them.

**Comment by TongZhai** [comment]
@dickinsonre glad to hear it is working. We are in the process of making another release with all up to date issue fixes.

**Comment by TongZhai** [comment]
MTP6r2 is released.
