### ISSUE TITLE
MTP6R0 and MTP6r1 crash while running Example6-final from the USEPA SWMM Applications Manual

### ISSUE THREAD

**Issue by sudhirkshirsagar** [USEPA/SWMM-EPANET_User_Interface#320]
It opens the file Example6-final.inp and displays it OK, but crashes while running it on a Window10 Pro machine. QGIS was installed to fix    the dependency related issue, and then the  UI came up. It does not crash with the Example1-post.inp from the Applications Manual.

**Comment by barrc** [comment]
I can reproduce the crash for Example6-Final.inp.  

Also, I get this console error when I load the file:

```
GEOS exception: UnsupportedOperationException: getX called on empty Point

GEOS exception: UnsupportedOperationException: getY called on empty Point
```

And this after pressing run:

```
Traceback (most recent call last):
  File "frmMainSWMM.py", line 1446, in run_simulation
  File "ui\frmMain.py", line 2299, in save_project
  File "frmMainSWMM.py", line 1689, in set_project_map_extent
  File "ui\map_tools.py", line 1694, in get_extent
IndexError: list index out of range
```

**Comment by TongZhai** [comment]
@barrc I found the reference to the said Example6-final.inp in the manual, but it doesn't have the actual input file listed, could you send the actual input file for us to debug?

**Comment by barrc** [comment]
@TongZhai here it is, please change the file extension to .inp

[Example6-Final.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/3962830/Example6-Final.txt)

**Comment by TongZhai** [comment]
@barrc this is due to failed subcatchment generation for a LID, the fix above allowed the run to succeed
