### ISSUE TITLE
SWMM LID control editor - pollutant removal tab

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#322]
I see Pollutant Removals was added as a tab in the LID control editor but I'm wondering if that was intentional?  I don't see a tab for that in the Delphi GUI and it doesn't seem like you can enter anything there.

Version: MTP6r1

**Comment by dickinsonre** [comment]
Pollutant removal in an LID was added by Lew Rossman for EPA SWMM 5.1.013 You see it in the Delphi Gui for some LID's if you have a pollutant. 
![image](https://user-images.githubusercontent.com/5599939/70130895-68851100-164f-11ea-887b-c972f3af36ba.png)

**Comment by barrc** [comment]
@dickinsonre thank you for pointing that out!  I think the editor needs to be tweaked slightly but I"ll look at how the Delphi GUI works and be more specific.

**Comment by PaulDudaRESPEC** [comment]
@barrc Have you had a chance to compare this editor to the Delphi version as you mentioned?  Perhaps you can do more testing here and see if you still see tweaks needed, otherwise this issue could be closed.

**Comment by barrc** [comment]
@PaulDudaRESPEC thanks for the reminder, this issue fell off my radar.  I will take a look this afternoon and either update or close.

**Comment by barrc** [comment]
In the Delphi GUI if there is no pollutant defined, the LID control editor looks like this for BR:
![image](https://user-images.githubusercontent.com/13906772/72574429-e0b13a00-387d-11ea-9afe-6a47aa0c2490.png)

vs in the new UI:
![image](https://user-images.githubusercontent.com/13906772/72574464-00e0f900-387e-11ea-82d8-d9cc42b2bfa5.png)

I can take a look at disabling the tab if there is no pollutant defined in the project and see if I can figure it out.
