### ISSUE TITLE
SWMM - can't use infiltration trench

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#324]
Infiltration trenches have a surface layer, storage layer, and optional drain layer.  These are showing up properly in the LID control editor but what is written to the inp file is

```
IT	IT
IT	SURFACE	4	0.0	0.1	1.0	5.0
IT	SOIL	0.0	0.5	0.2	0.1	0.5	10.0	3.5
IT	DRAIN	0.0	0.5	6.0	6.0	0	0	
```

where there is a soil layer instead of a surface layer.  This produces an ERROR 184: missing layer for LID IT when you try to run the simulation.  To reproduce create a simple model with an infiltration trench.

Version: MTP6r1

**Comment by PaulDudaRESPEC** [comment]
Indeed that is a bug, just verified and fixed.
