### ISSUE TITLE
Problems with Map scaling in and out

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#325]
Each time I add a new feature or run the program, the view abruptly changes.  It is hard to test.

**Comment by TongZhai** [comment]
@michelleannesimon @barrc please give this a try to confirm the fix. thanks.

**Comment by barrc** [comment]
@TongZhai @michelleannesimon this is working in my development environment.

**Comment by fdumont7** [comment]
@TongZhai @barrc I tested this in my development environment with @michelleannesimon last week and again today and it is working for me.

**Comment by barrc** [comment]
thanks @fdumont7 I'll close this then.
