### ISSUE TITLE
Vector layer disappears after adding object and opening editor

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#329]
This is an odd bug but I have seen it with a couple different shapefiles and objects.  

To reproduce:
- Add a vector layer (shapefile)
- Confirm the shapefile appears under Layers -> Others
- Add two junctions and a conduit 
- Open the junction editor for one of the created junctions to see its properties
- Press OK
- The shapefile is no longer shown
- Confirm the shapefile no longer appears under Layers -> Others

Version: SWMM MTP6r1

**Comment by TongZhai** [comment]
@barrc please give this a try to confirm the fixes. thanks.

**Comment by barrc** [comment]
@TongZhai looks good to me -- I'll close the issue.
