### ISSUE TITLE
Study area map "unmaximizes" after every simulation is run

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#330]
If I have the SWMM UI maximized, every time I run a simulation it becomes "unmaximized".  The program shouldn't change its state unless the user asks.  I don't think this happened with older versions of the UI.

Before:
![image](https://user-images.githubusercontent.com/13906772/72394901-9fd5eb80-36ec-11ea-9771-25d06ed4a099.png)

After:
![image](https://user-images.githubusercontent.com/13906772/72394917-abc1ad80-36ec-11ea-8a39-3aed25c83edf.png)

Version: MTP6r1

**Comment by TongZhai** [comment]
@barrc very interesting. Apparently, it seems that it only does this when the main window is maximized, any other size window won't get resized when running simulation.

**Comment by barrc** [comment]
@TongZhai that's correct.  I was looking at the code and I think it's happening in the below section of frmRunSWMM.py, specifically the statement in the try/except block.  If you get rid of the try/except block the window doesn't get resized and it doesn't seem to cause any problems, but I'm not sure the difference between the two showNormal calls so not sure?

```
        if self._main_form:
            try:
                self._main_form.showNormal()
            except:
                pass
        self.showNormal()
```

**Comment by TongZhai** [comment]
@barrc thanks for the tip, I will take a look at this.

**Comment by TongZhai** [comment]
@barrc you are right, the _main_form is referencing the main window of the application and you are also right in that there is no particular reason for it, so that action is removed. Please help confirm this fix, you can close the issue afterwards, thanks.

**Comment by barrc** [comment]
@TongZhai tested successfully in my development environment so I'll close the issue.  Thanks!
