### ISSUE TITLE
Add objects through tree diagram confused when switching between objects

### ISSUE THREAD

**Issue by PaulDudaRESPEC** [USEPA/SWMM-EPANET_User_Interface#331]
Adding objects to the SWMM map using the tree diagram works when using the green + sign before adding each item, but it can get confused when adding one form of visual object (subcatchments) and then switching to another form of object (say junctions) without clicking the green sign in between.  The sequence works fine when using the toolbar buttons.

**Comment by PaulDudaRESPEC** [comment]
Problem solved by adding a call to the same one used by the toolbar buttons.

**Comment by TongZhai** [comment]
@PaulDudaRESPEC @barrc  @michelleannesimon the fix above standardizes the use of the green plus button to add new model elements from the tree diagram, hence eliminates confusion when selection changes in the tree diagram. Also, users can freely intertwine selection/switching of model element using the toolbar icons as well. Please help confirm.

**Comment by barrc** [comment]
Tested successfully in my development environment.
