### ISSUE TITLE
Updated instructions for creating install packages

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#332]
Are there updated instructions for creating the install packages with the new development stack?  Basically this Wiki page: https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Creating-install-packages-for-Windows but for Python 3/qgis3/qt5.

**Comment by TongZhai** [comment]
[New instruction for creating installation packages for the python 3 and Qt 5 code base](https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Create-Installation-Package-for-Windows-10-(python-3-Qt-5-version) is created.
