### ISSUE TITLE
Non-default infiltration methods sometimes not written to inp file

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#333]
When creating projects from scratch, it seems like sometimes the infiltration section is not being written to the input file if it is not the default infiltration method.

I noticed this while working through a tutorial and seeing in the results that all my subcatchments had 0 infiltration when I used MODIFIED_GREEN_AMPT as the infiltration method, but I think the following steps should be a simpler way to reproduce:
- Create a project
- Project -> Defaults -> Infiltration Method -> MODIFIED_GREEN_AMPT -> OK -> OK
- Create subcatchment
- Save project 
- Open inp file and look at [INFILTRATION] method, it is blank (if you want, add a rain gage/outfall and run a simulation and check infiltration in the results)

Please let me know if you can't reproduce.

Version: SWMM MTP6r1 and current dev-ui-py3qt5

**Comment by PaulDudaRESPEC** [comment]
@barrc I can reproduce this one and it should be a very quick fix -- for whatever reason it is only the MODIFIED_GREEN-AMPT that has this issue.

**Comment by PaulDudaRESPEC** [comment]
I just committed a fix for this issue, @barrc please verify in the development environment that it is indeed fixed and close if satisfied.

**Comment by barrc** [comment]
Thanks @PaulDudaRESPEC -- I tested successfully, closing the issue.
