### ISSUE TITLE
Opening editors can lead project to think there have been changes

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#341]
If you load a file (for example Example1.inp), then run it, everything works.  If you then start opening some editors to look at the parameters and click "OK" (you should probably click "Cancel" instead of "OK" if you haven't changed anything, but people will click "OK"), sometimes the program thinks that your project has changed.

One aspect of this seems to be that the program is comparing an Enum to a str(Enum) when it checks if things have changed but there might be other things going on too.  

Version: SWMM MTP6r2

**Comment by barrc** [comment]
Some other parameters that cause this:

| Editor | Parameter | new_value | old_value |
| ------ | -------- | ---- | ---- |
| Outfall | Tide Gate | 'NO' | 'False' |
| Outfall | Curve Name | '*' | 'None' |
| Outfall | Series Name | '*' | 'None' |
| Pollutant | Snow Only | False (bool) | 'False' |

**Comment by PaulDudaRESPEC** [comment]
All SWMM forms have been rechecked for this condition.
