### ISSUE TITLE
Input files that run long lock up

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#349]
I have a couple of input files that run long and lock up.  I cannot stop and I cannot minimize.
![image](https://user-images.githubusercontent.com/26123284/73395764-26bec280-42ae-11ea-8e3c-a89fe8d69c05.png)  Here is an input file converted to txt

[3SecondPulse_EXAMPLE_SW5.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/4130670/3SecondPulse_EXAMPLE_SW5.txt)

**Comment by barrc** [comment]
closed by #359
