### ISSUE TITLE
Creating plots can fail if you have viewed a timeseries

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#353]
To reproduce:
- run Example1.inp
- go to timeseries editor and view the timeseries
- create a scatter plot or timeseries plot (crash)

If you skip viewing the timeseries, you can create a scatter plot or timeseries plot.

```
Traceback (most recent call last):
  File "site-packages\matplotlib\figure.py", line 432, in show
AttributeError: 'CurvePlot' object has no attribute 'manager'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "frmTimeSeriesPlot.py", line 91, in cmdOK_Clicked
  File "core\graph.py", line 123, in plot_time
  File "site-packages\matplotlib\pyplot.py", line 253, in show
  File "site-packages\matplotlib\backend_bases.py", line 3248, in show
  File "site-packages\matplotlib\figure.py", line 437, in show
AttributeError: 'CurvePlot' object has no attribute 'manager'
Figure.show works only for figures managed by pyplot, normally created by pyplot.figure().
'CurvePlot' object has no attribute 'manager'
Figure.show works only for figures managed by pyplot, normally created by pyplot.figure().
None
```

Version: SWMM MTP6r2 and dev-ui-py3qt5

**Comment by barrc** [comment]
This [stackoverflow comment](https://stackoverflow.com/questions/17973177/matplotlib-and-pyqt-dynamic-figure-runs-slow-after-several-loads-or-looks-messy#comment26295260_17973177) makes it sound like we shouldn't be importing pyplot?  Maybe see [this tutorial](https://matplotlib.org/examples/user_interfaces/embedding_in_qt5.html).  At some points the GUI is using matplotlib.figure instead of plt.figure (whre plt is matplotlib.pyplot).

**Comment by PaulDudaRESPEC** [comment]
It looks like the plots produced by frmPlotViewer.py (like the timeseries editor) have this issue.  I suspect an upgrade to matplotlib has something to do with it, because this all worked not long ago.  I think the solution may to follow the model of the output timeseries and scatter plots.

**Comment by PaulDudaRESPEC** [comment]
The commit referenced above satisfies the initial issue.  You can now:
run Example1.inp
go to timeseries editor and view the timeseries
create a scatter plot or timeseries plot!
