### ISSUE TITLE
Custom cross sections can cause errors

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#356]
The SWMM 5.1 user's manual gives the format for custom cross sections as:
`Link CUSTOM Geom1 Curve (Barrels)`

The new UI seems to write custom xsections that follow the user's manual.  

When I run a simulation I get an error:
```
  ERROR 203: too few items at line 64 of [XSECT] section:
  Conduit1        	CUSTOM      	5               	3         	1         
```

The old UI writes custom xsections like this:
```
[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   
;;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------
1                CUSTOM       1                test       0          0          1                    
```

It seems like that SWMM might expect those 0s.  [I think this is the relevant SWMM code for parsing this part of the inp file](
https://github.com/USEPA/Stormwater-Management-Model/blob/909cfbbdf0edcc83f11b02444982953f69e159cc/src/library/link.c#L170)

**Comment by PaulDudaRESPEC** [comment]
@barrc I've committed a fix for the issue, maybe you can verify that this indeed addresses the issue and close if appropriate.

**Comment by barrc** [comment]
@PaulDudaRESPEC this seems to fix the issue, thanks!
