### ISSUE TITLE
Can't open editor for orifice more than once

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#362]
To reproduce:
- Create two nodes and draw an orifice between them
- Open the orifice editor for the new object
- Click ok
- Try to open the editor again; nothing happens

Version: SWMM MTP6r2

**Comment by TongZhai** [comment]
@barrc The update fixed a problem in the orifice editor's xsection assignment due to qt5 change of behavior, please give it a try, you can close if no issue.

**Comment by barrc** [comment]
Tested successfully.
