### ISSUE TITLE
Green, Light blue, and Yellow Labels on Maplayer are too light to read

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#364]
![image](https://user-images.githubusercontent.com/26123284/73873450-9f2e0200-481f-11ea-8bed-f85a4f1c11e7.png)

**Comment by barrc** [comment]
@michelleannesimon I can take a look at changing the colors.  

Do we want to keep the color scale similar to the old UI or change it up?  The old color scale was:
![image](https://user-images.githubusercontent.com/13906772/73877531-b06e1300-480d-11ea-9ad8-b6e6777e35f5.png)

**Comment by michelleannesimon** [comment]
let's keep the old one.

**Comment by barrc** [comment]
@michelleannesimon I think I'll have to change it slightly because the yellow, light blue, and green are hard to read but I'll try to choose darker versions of those colors.  Let me know if I'm misunderstanding.

**Comment by michelleannesimon** [comment]
Similarly, there is not enough contrast in the Time Series Plot Legend.

![image](https://user-images.githubusercontent.com/26123284/74196209-c115f300-4c2a-11ea-981e-3025e80e9ed3.png)

**Comment by barrc** [comment]
Initial issue closed by #381.  Time series plot legend moved to separate issue for tracking.
