### ISSUE TITLE
Missing land elevation and HGL line on profile

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#365]
!
![image](https://user-images.githubusercontent.com/26123284/73873962-a1449080-4820-11ea-836f-afb8a52b4298.png)

**Comment by michelleannesimon** [comment]
The dotted line my be the HGL but the land elevation is missing.

**Comment by PaulDudaRESPEC** [comment]
It looks like our earlier versions of the profile plot had the HGL, but broke somehow as we moved to python 3 and newer versions of matplotlib.  A comment in our UI says "Profile plot based on 'Basic HGL 2-D Video Profile Plot Script by Bryant E. McDonnell'" -- maybe an updated version of that script would help here.

**Comment by PaulDudaRESPEC** [comment]
The commit above puts the HGL back on the plot.  Strangely in the debug environment the plot keeps updating each time step (animating), but not when running.
![image](https://user-images.githubusercontent.com/13470278/83809912-44010480-a685-11ea-90f0-e0be08edd3e4.png)

**Comment by michelleannesimon** [comment]
This appears to be working properly in MTP7r0.  I will close this issue.
