### ISSUE TITLE
Frequency Plot in Statistics Tab does not work

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#366]
I have tried a couple of input files:  I was expecting
![image](https://user-images.githubusercontent.com/26123284/73876097-5a589a00-4824-11ea-8483-f8b8fe020a19.png)
but I get a blank screen
![image](https://user-images.githubusercontent.com/26123284/73876173-8d9b2900-4824-11ea-8cf5-ee3fc5110c65.png)

**Comment by barrc** [comment]
closed by #368
