### ISSUE TITLE
Custom pipe shapes don't import correctly / newbie questions

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-EPANET_User_Interface#367]
I've just found this project, after having heard about it for several years. I tried loading a couple of my models and have compiled a dozen or so issues, none of which I see in the discussions here. Should I list each one as a new issue in this forum? I can post example files if that would help.

Here's one of them. My existing input file contains:

[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert
;;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------
GIS1000950       CUSTOM       2.25             ParkAveCombo_1Inch 0          0          1                    

This becomes:

GIS1000950      	CUSTOM      	2.25            	ParkAveCombo_1Inch	1  

which throws an error in SWMM.

**Comment by dickinsonre** [comment]
There was a typo in the 2015 Users manual for this - it looks like Geom4 and Barrels are not being read properly

Section: [XSECTIONS] 
Purpose: Provides cross-section geometric data for conduit and regulator links of the drainage system. 
The description for Custom and irregular is incomplete, Here is how it is listed in the User Manual
Formats: Link Shape Geom1 Geom2 Geom3 Geom4 (Barrels Culvert) 
Link CUSTOM Geom1 Curve (Barrels) 
Link IRREGULAR Tsect

It would be better to show how it is actually used (here is an example)

Formats: [XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert   
;;-------------- ------------ ---------------- ---------- ---------- ---------- ---------- ----------
8040             CUSTOM       4                CustomShape 0          0          1                    
8060             CIRCULAR     4                0          0          0          1                    
8100             IRREGULAR    HECRAS           0          0          0          1                    
8130             CIRCULAR     4.5              0          0          0          1                    
1030             TRAPEZOIDAL  9                0          3          3          1                    
Suggestion:  Change the User Manual to show this instead
Formats: Link Shape Geom1 Geom2 Geom3 Geom4 (Barrels Culvert) 
Link CUSTOM Geom1 Curve Geom3 Geom4 (Barrels Culvert)
Link IRREGULAR Tsect  Geom2 Geom3 Geom4 (Barrels Culvert)

**Comment by barrc** [comment]
@MitchHeineman thanks for reporting.  It would be great if you could open a new issue for every issue you encounter.  Example files are definitely helpful for reproducing and debugging.  

I think we just addressed this specific issue (in #356) so the fix should be in the next MTP release.

@dickinsonre thanks for pointing out that problem with the manual.  We may need to double check IRREGULAR cross sections as well in case they are following the manual's specifications.

**Comment by dickinsonre** [comment]
just to be clear,  actually, Feng Sheng then of Innovyze and now with EPA found that typo.  I was just copying what he said.

Great job of helping with this GUI @barrc !
