### ISSUE TITLE
Daily [PATTERNS] printing on two lines

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-EPANET_User_Interface#369]
This is just an annoyance, as it works fine, but detracts from the readability of the text input file. A DAILY flow pattern that looks like this in my original input

[PATTERNS]
;;Name           Type       Multipliers
dayWH1           DAILY      0.3   1.3   1.3   1     1.33  1.2   0.42

becomes this when saved from the GUI:

dayWH1           DAILY      0.3   1.3   1.3   1     1.33  1.2   
dayWH13         0.42

Since there are always seven days in a week, the program should be formatted to print all seven entries on a single line.

**Comment by barrc** [comment]
Closed by #383
