### ISSUE TITLE
SWMM Climatology Editors: some are not saving changes

### ISSUE THREAD

**Issue by TongZhai** [USEPA/SWMM-EPANET_User_Interface#37]
evaporation, wind speed, snow melt, areal depletion are not saving changes

**Comment by TongZhai** [comment]
the official EPA SWMM program does not save wind speed values

**Comment by dickinsonre** [comment]
Yes, you are right - the current EPA SWMM 5.1.011 Delphi GUI does not save Wind Speed values.  It did at one time a few years ago so it must have gotten broken when Delphi XE2 was used for SWMM 5.1

**Comment by PaulDudaRESPEC** [comment]
From my testing I see that if the user does not specify a source of temperature data, the other climate data does not get saved.  This appears to be by design, as the Delphi GUI behaves the same way.  Therefore this issue can be closed.
