### ISSUE TITLE
[AQUIFERS] can't be edited in large model

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-EPANET_User_Interface#371]
In a model with a single Aquifer, the editor works fine. In models I tested with 200 and 4000 aquifers however, the list of Aquifers is displayed, but I can neither add new ones nor edit existing ones.

**Comment by TongZhai** [comment]
@MitchHeineman I tested on a model that has 116 subcatchments and each has an aquifer, I had no trouble editing existing ones and adding new ones. If possible, could you send us an example of your model that had this problem? I suppose you can strip it down to just having the subcatchments and aquifers that still can reproduce this problem.

**Comment by MitchHeineman** [comment]
You're right - it has nothing to do with the number of aquifers. It's something about introducing [Patterns]. The example below loads successfully as-is. If I activate the Daily1 pattern though (i.e. remove the comment semi-colon), I can't edit the Aquifer properties.

[RAINGAGES]
BostonNWS        VOLUME    01:00  0      FILE       Boston190770.NCD BostonNWS  IN   

[SUBCATCHMENTS]
Area1D           BostonNWS        Area1D            40       25       50       0.5      0                        
 
[AQUIFERS]
AQ1	0.45	0.11	0.25	0.37	10	15	0.35	6	0	0	7	0.25

[GROUNDWATER]
Area1D           AQ1             dummy            15     0.001  2      0      0      0      0      6     

[PATTERNS]
;Daily1           DAILY      1.12  1.1   1.07  1     0.87  0.99  0.85

**Comment by TongZhai** [comment]
@MitchHeineman Thanks for you diligence in discovering this bug, which is addressed by above update.
