### ISSUE TITLE
Importing [GWF] throws unrecognized keyword warning

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-EPANET_User_Interface#372]
Loading a model that has a [GWF] section produces a SWMM Warning dialog box with the content Unrecognized keyword ([GWF]). After clicking past the error, the model loads. The GWF equations are not visible in the Groundwater Flow Editor, although they show up when the .inp is generated for a simulation.

[RAINGAGES]
LongTerm     VOLUME    00:15    1        FILE       LongTerm.dat  1          IN   

[SUBCATCHMENTS]
4000   LongTerm   4000     75  23       5        0.1      0                        

[AQUIFERS]
4000     0.45   0.25   0.33   2      40     0      0.5    10     0.001  999    999    0.32         

[GROUNDWATER]
4000  4000 4000     56     7.4e-05 1.3    0      0      0      0      35     30     48.11  0.33  

[GWF]
;;Subcatchment   Flow    Equation
;;-------------- ------- --------
4000 DEEP  0*(Hgw-Hcb)^1.3+0.001*Hgw/Hgs + 0.1*(Hgw-Hcb-5)^1.5*step(Hgw-Hcb-5)

**Comment by barrc** [comment]
I can reproduce this and I'm looking into it.

**Comment by PaulDudaRESPEC** [comment]
Updates by @barrc resolve this issue.
