### ISSUE TITLE
Clicking View on a Transect crashes program

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-EPANET_User_Interface#374]
This transect is a legitimate input file, that loads without issue, but crashes the program when one clicks the View button in the Transect editor

[TRANSECTS]
NC 0.05     0.05     0.05    
X1 1                 12       -1020    700      0.0      0.0      0        1        0       
GR 50       -1020    49       -980     47       -830     46       -740     45       -5      
GR 44       0        45       5        46       280      47       430      48       540     
GR 49       640      50       700     

Version MTP6r2

**Comment by PaulDudaRESPEC** [comment]
I think this is the same as closed issue #334

**Comment by michelleannesimon** [comment]
Which version of the GUI are you working with Mitch?
MTP6r2 released on Jan 22, 2020?

**Comment by MitchHeineman** [comment]
Yes. I added that to the issue I created about transects, and will remember to do in the future.

**Comment by PaulDudaRESPEC** [comment]
This issue has been resolved in the current development version.
