### ISSUE TITLE
Description I/O problems for [Landuses]

### ISSUE THREAD

**Issue by MitchHeineman** [USEPA/SWMM-EPANET_User_Interface#378]
Two part issue:
- Existing descriptions are not read from the [Landuse] section of an input file. 
- Descriptions are written from the GUI without leading semi-colons.

Example input:

[LANDUSES]
;;               Cleaning   Fraction   Last      
;;Name           Interval   Available  Cleaned   
;;-------------- ---------- ---------- ----------
;Commercial only
Commercial       14         0.8        7         
;Forest and five other categories. Not swept
ForestUndeveloped 0          0.8        0 
;Transportation and Marina
Transportation   14         0.8        7         

A simple read/write operation retains the first description (although it's not visible in the GUI). Note also the unneeded space inserted before each item.

[LANDUSES]
;;               Cleaning   Fraction   Last
;;Name           Interval   Available  Cleaned
;;-------------- ---------- ---------- ----------
;Commercial only
 Commercial     	14        	0.8       	7         
 ForestUndeveloped	0         	0.8       	0         
 Transportation 	14        	0.8       	7  

Descriptions created in the GUI are exported, but without required semi-colons:
[LANDUSES]
;;               Cleaning   Fraction   Last
;;Name           Interval   Available  Cleaned
;;-------------- ---------- ---------- ----------
;Commercial only
test1
 Commercial     	14        	0.8       	7         
test2
 ForestUndeveloped	0         	0.8       	0         
test3
 Transportation 	14        	0.8       	7

**Comment by TongZhai** [comment]
The above update allows SWMM to handle reading, writing, and displaying multiline comment per landuse.
