### ISSUE TITLE
Map Layer does not show flow direction

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#385]
Or present legend for colors

**Comment by TongZhai** [comment]
@michelleannesimon after simulation, on the 'Map' tab, there is a checkbox for 'Show Flow Direction', when you check it, it will show flow direction on map, also the color of the arrow will change according to the numerical gradation based on chosen output. Here is a screen grab:
![image](https://user-images.githubusercontent.com/16242714/74282940-069bf400-4cef-11ea-9d63-1122d8fa5d96.png)

**Comment by michelleannesimon** [comment]
I see.  I will close this issue.
