### ISSUE TITLE
EPANET Export Map Feature to GIS Not Working

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#387]
MTP6r2 - File menu/Export/Map - select Shapefiles does not seem to work.  Only the pipes layer seems to be produced and then the problem freezes up.   In the command window, the following is provided:
File "ui\frmMain.py", line 456, in export_to_gis
  File "ui\import_export.py", line 318, in export_to_gis
  File "ui\import_export.py", line 338, in export_epanet_to_gis
  File "ui\import_export.py", line 511, in export_links_layer
  File "ui\import_export.py", line 482, in write_layer
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'c:/users/.../FortCampbell_EPS_ADD_pipes.qpj'

I believe I recall this working in an earlier release?

**Comment by TongZhai** [comment]
@rjanke20 Yes, I can reproduce this bug in the installed version, however exporting to shapefile doesn't fail in the development environment though.

**Comment by PaulDudaRESPEC** [comment]
When I run EPANET in our dev environment, I can go to View:Translate Coordinates and set the CRS like this:
![image](https://user-images.githubusercontent.com/13470278/82734052-35f6cf80-9ce6-11ea-97b7-405f33f29e44.png)

But when I do that in the installed version, it doesn't load the projection options:
![image](https://user-images.githubusercontent.com/13470278/82734076-54f56180-9ce6-11ea-8162-2aaeaced93a2.png)

I have a hunch that this is a clue related to some GIS things working in the development environment but not in the installed version.  Does anyone else see this symptom and have any insights?

**Comment by PaulDudaRESPEC** [comment]
I find that if I copy the 'resources' folder from 
C:\OSGeo4W64\apps\qgis\resources
to my installed EPANET-UI folder, the 'export to shapefile' option works!  

So I think this issue comes down to having all the necessary files put into the installation package.

It doesn't fix the coordinate reference system dialog problem I noted above though, so there may be more files that need to go into the package.

**Comment by TongZhai** [comment]
This can be resolved by copying `C:\OSGeo4W64\apps\qgis\resources\` folder into `*-UI\` folder in the installed version.
