### ISSUE TITLE
Illegal values are set for new pipes

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#39]
Illegal values are set for new pipes: diameter, length, roughness

**Comment by MarkGrayRESPEC** [comment]
There is not yet an interface for specifying default values for attributes, so these are by default set to zero. These can be updated by editing the attributes of a pipe.

**Comment by eladsal** [comment]
Even default values should have defaults :)

I [added](https://github.com/OpenWaterAnalytics/EPANET/commit/c3d3e9101864f32aa5d0f33285899179da921cef) defaults for the open source dll.

**Comment by TongZhai** [comment]
The default editor for both EPANET and SWMM are functional and the visual model objects are created with common properties populated with sensible defaults now.

**Comment by eladsal** [comment]
This problem returned in MTP4r2. New pipes properties are set to zero.

**Comment by eladsal** [comment]
Hmm, after the first time I saved a network the defaults were created.
