### ISSUE TITLE
Statistics summary report histogram y limit

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#393]
The y limit in the histogram plot is too high:

![image](https://user-images.githubusercontent.com/13906772/74558950-14808d80-4f18-11ea-994f-e9c3b185cebd.png)

Version: SWMM MTP6r2

**Comment by dickinsonre** [comment]
In the Delphi GUI this is either 100 or the peak value.  IMO, it should be 100 percent for all so you can compare different histograms.

**Comment by barrc** [comment]
@dickinsonre I think it's the peak value in the Delphi GUI:
![image](https://user-images.githubusercontent.com/13906772/74563282-4ba76c80-4f21-11ea-8be7-687e5148ce9a.png)

I think making the y limit 100% is reasonable.  But it might be hard to see variation if the events are fairly evenly distributed around a lower number.  I don't have a strong opinion here, but 4000% is clearly not helpful :)

**Comment by MitchHeineman** [comment]
The x-axis should not extend past zero either

**Comment by barrc** [comment]
Michelle recommended we set the limit at 100%.

**Comment by barrc** [comment]
closed by #396
