### ISSUE TITLE
Problem creating objects with non-default name when made by clicking on three dots

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#395]
To reproduce:
- Open Climatology editor on Temperature tab
- Select the radio button for Time Series 
- Click the three dots to launch the Time Series editor
- Change the time series name and enter some data into the table
- Click OK
- The name of the time series is correct on the lower left hand corner of the screen but is still the default in the Climatology editor

If you click OK to close the Climatology editor, then re-open, no time series is selected but the correct name for the time series was added to the drop down menu.

This seems to apply for other objects that are created by launching the dialog from the three dots too (evaporation time series, evaporation monthly soil recovery pattern, irregular transects, not sure if there are more).

Version: SWMM MTP6r2 and current dev-ui-py3qt5

**Comment by PaulDudaRESPEC** [comment]
@barrc I fixed each of the instances you mentioned -- temperature time series, evaporation time series, evaporation monthly soil recovery pattern, irregular transects -- if you find more let me know.
![image](https://user-images.githubusercontent.com/13470278/82004754-adb36300-9631-11ea-8929-9105a2067329.png)
