### ISSUE TITLE
MAP Projections

### ISSUE THREAD

**Issue by michelleannesimon** [USEPA/SWMM-EPANET_User_Interface#407]
I see that the project for the map is EPSG:4326.  Can this be changed?  It does not seem to register when I change dimensions onto it.  I have been researching https://github.com/fitnr/mxd2qgs

**Comment by PaulDudaRESPEC** [comment]
seems like the projections database is missing

**Comment by michelleannesimon** [comment]
I cannot see how to bring in a georeferenced Basemap, with a projection, and calculate subcatchment widths and areas.

The ImportExportGIS does not work with many ArcGIS files, such as jpeg with world coordinates, only GeoJSON files.

The export function only goes to GeoJSON and also does not seem to work.

**Comment by PaulDudaRESPEC** [comment]
seems related to issue #387

**Comment by PaulDudaRESPEC** [comment]
The area calculation for a new subcatchment is working for me in the development environment, but not in the installed package.  

To test the feature, I open an empty SWMM project, go to Map/Backdrop in the Project Explorer Options, set the distance units to feet or meters, and then add the subcatchment.  When I look at the area term for the subcatchment, the area appears to be calculated from the geometry.

**Comment by TongZhai** [comment]
This can be resolved by copying `C:\OSGeo4W64\apps\qgis\resources\` folder into `*-UI\` folder in the installed version.
