### ISSUE TITLE
SWMM help - the page could not be found

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#409]
When I try to access Help -> Help Topics from SWMM MTP6r2, I get an error that says: 

The page could not be found.
'qthelp://swmm/src/src/swmmsmainwindow.htm'

The Contents and Index are blank.

![image](https://user-images.githubusercontent.com/13906772/76234578-21c32c00-61e7-11ea-80de-5ff11192a80a.png)

From dev-ui-py3qt5, when I do Help -> Help Topics, nothing happens.

**Comment by PaulDudaRESPEC** [comment]
the help works here, I think there may be some sort of registration process that needs to happen for it to show up

**Comment by PaulDudaRESPEC** [comment]
@michelleannesimon -- from what we saw yesterday we know Help isn't working in your development environment, and presumably your installed version too.  To help us get to the root of the problem, could you answer a few questions for us?

When I start SWMM in the development environment, in the pycharm console window at the bottom of the screen I see these messages:

HelpHandler.help_assistant_executable = C:/OSGeo4W64/apps/Qt5/bin/assistant.exe
HelpHandler.help_assistant_arguments[1] = C:\dev\Python\dev-ui-py3qt5\src\ui\SWMM\swmm.qhc

You should see similar messages for the locations of assistant.exe and swmm.qhc on your computer.  Could you check for us if those files actually exist in those locations?  

Similarly, when I run the installed version, I see these messages in the 'DOS-box like' window while the UI is initializing:

HelpHandler.help_assistant_executable = C:\Program Files\SWMM-UI\assistant.exe
HelpHandler.help_assistant_arguments[1] = C:\Program Files\SWMM-UI\swmm.qhc

Do you see those messages too?  And do those files actually exist in those locations?  

Thank you for your help -- we certainly want to get to the bottom of this one!

**Comment by michelleannesimon** [comment]
Hello Paul,
I am current as of 5/10/2020 in the dev-ui-py3qt5 brnach of the GUI, as of (gitbash > git pull > you are current)
I run the attached batch file
[env_init_mas - Copy.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/4623653/env_init_mas.-.Copy.txt)

here is what I get in my pycharm console:
C:\OSGeo4W64\apps\Python37\pythonw.exe C:/Users/MSIMON/Documents/SWMMUI/devSWMM-UI/SWMM-EPANET_User_Interface/src/ui/SWMM/frmMainSWMM.py
QApplication
internationalization
frmMainSWMM
Read program settings from C:/Users/MSIMON/AppData/Roaming/EPA/SWMM.ini
QsciScintilla.SC_TYPE_STRING:
2
Original Path = C:\OSGeo4W64\apps\qgis\bin;C:\OSGeo4W64\apps\qgis\python\PyQt5;C:\OSGeo4W64\apps\Python37;C:\OSGeo4W64\apps\Python37\Scripts;C:\OSGeo4W64\apps\Qt5\bin;C:\OSGeo4W64\apps\qt5\plugins;C:\OSGeo4W64\bin;;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Git\cmd;C:\Users\MSIMON\cmake-3.13.5-win64-x64\bin;C:\Program Files\McAfee\Solidcore\Tools\GatherInfo;C:\Program Files\McAfee\Solidcore\Tools\Scanalyzer;C:\Program Files\McAfee\Solidcore\;C:\Program Files\McAfee\Solidcore\Tools\ScGetCerts;C:\Users\MSIMON\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\bin;;C:\OSGeo4W64\apps\Python37\Scripts;;C:\OSGeo4W64\apps\Python37\lib\site-packages\pywin32_system32;C:\OSGeo4W64\apps\Python37\lib\site-packages\numpy\.libs
Search C:\OSGeo4W64\apps\qgis
Try path = C:\OSGeo4W64\apps\qgis;C:\OSGeo4W64\apps\qgis\bin;C:\OSGeo4W64\bin;C:\OSGeo4W64\apps\qgis\bin;C:\OSGeo4W64\apps\qgis\python\PyQt5;C:\OSGeo4W64\apps\Python37;C:\OSGeo4W64\apps\Python37\Scripts;C:\OSGeo4W64\apps\Qt5\bin;C:\OSGeo4W64\apps\qt5\plugins;C:\OSGeo4W64\bin;;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\Git\cmd;C:\Users\MSIMON\cmake-3.13.5-win64-x64\bin;C:\Program Files\McAfee\Solidcore\Tools\GatherInfo;C:\Program Files\McAfee\Solidcore\Tools\Scanalyzer;C:\Program Files\McAfee\Solidcore\;C:\Program Files\McAfee\Solidcore\Tools\ScGetCerts;C:\Users\MSIMON\AppData\Local\Microsoft\WindowsApps;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2\bin;;C:\OSGeo4W64\apps\Python37\Scripts;;C:\OSGeo4W64\apps\Python37\lib\site-packages\pywin32_system32;C:\OSGeo4W64\apps\Python37\lib\site-packages\numpy\.libs
DBG: import qgis core gui passed.
DBG: import map_tools passed.
Found QGIS in C:\OSGeo4W64\apps\qgis
Read project settings from C:/Users/MSIMON/AppData/Roaming/pythonw/profiles/default/EPA/swmm.ini
**HelpHandler.help_assistant_executable = /assistant.exe
HelpHandler.help_assistant_arguments[1] = C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface\src\ui\SWMM\swmm.qhc**
show

**Comment by PaulDudaRESPEC** [comment]
Thanks, @michelleannesimon , that's helpful.  Your system is a little different from mine because you are starting using that "env_init_mas - Copy.txt" script, so I can't do exactly what you are doing, but I think I can see enough.  

The first issue is that your computer is not finding the file 'assistant.exe', which is the Qt Help Assistant.   One way to resolve that would be to follow step c in the instructions on the "https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Create-Installation-Package-for-Windows-10-(python-3-Qt-5-version)" page, which says:

c). Put the following files into 'C:\OSGeo4W64\apps\Qt5\bin' folder: assistant.exe, Qt5Help.dll (the links to the files are there).  

I think if you do that you'll be across the first hurdle.  When you run your development environment again, then then access the 'Help' menu, you should see Colleen's first image above.  When you get there, let me know and I'll help you across the next hurdle.

**Comment by michelleannesimon** [comment]
This is what I have from the installed version from 1/23/2020 swmm-ui (https://github.com/USEPA/SWMM-EPANET_User_Interface/files/4624074/installedswmm-ui20200406.docx)

**Comment by michelleannesimon** [comment]
Paul,

I do have in my directory  'C:\OSGeo4W64\apps\Qt5\bin' folder: assistant.exe, Qt5Help.dll

**Comment by PaulDudaRESPEC** [comment]
@michelleannesimon, from the doc you sent earlier today, it appears you can access the updated user's manual from the installed version of the software.  If you scroll down on the main page you should see added text that applies to this version of the software, and many other pages have images updated.

**Comment by PaulDudaRESPEC** [comment]
@barrc, if you see that "The page could not be found" message, that tells us that the Qt Help Assistant has been installed, but that the help file itself can't be found.  You can type "assistant -register swmm.qch" from a command prompt in the installation folder, and that should make the help file available within Qt Assistant.

**Comment by michelleannesimon** [comment]
the version that we six created on 4/2/2020 SWMM-UI, the :Help Topics" works.  
Just now, I updated my dev-ui-py3qt branch and ran my batch file.  When I hit "Help Topics"  Nothing happens.

**Comment by michelleannesimon** [comment]
I went to the command prompt: and here is what happens:


C:\windows\system32>cd "C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface"

C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface>assistant -register swmm.qch
'assistant' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface>

**Comment by PaulDudaRESPEC** [comment]
It's a little hard to tell what's going on since your system is different, but the 'register' process should work if it can find these files:
assistant.exe
Qt5Help.dll
swmm.qch
swmm.qhc

You could try copying all of them into this folder:
C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface>

And then run again:
assistant -register swmm.qch

**Comment by michelleannesimon** [comment]
All of these files were in C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface\src\ui\SWMM\dist\SWMM-UI

I have copied them to C:\Users\MSIMON\Documents\SWMMUI\devSWMM-UI\SWMM-EPANET_User_Interface

I am not able to see the help from the dev-ui-py3qt5 branch
![help](https://user-images.githubusercontent.com/26123284/82057052-d3238980-9690-11ea-93ee-bb87b256a553.png)

**Comment by PaulDudaRESPEC** [comment]
as per discussion with @michelleannesimon  on 5/15/2020, the documentation is now working.
