### ISSUE TITLE
Mac build for testing?

### ISSUE THREAD

**Issue by samhatchett** [USEPA/SWMM-EPANET_User_Interface#41]
A mac binary would be quite helpful. I don't have a win environment and I've tried to get a build env set up on Mac with no success - many dependencies and conflicts. Alternatively, a better description of how a Mac env should be configured?

**Comment by MarkGrayRESPEC** [comment]
We hope to work on a Mac version but have not gotten started on that yet. Anyone who is a Mac developer interested in this project, please leave a comment.

**Comment by poVoq** [comment]
A Linux build would be also appreciated.

**Comment by michaeltryby** [comment]
@poVoq We would be happy to support volunteer work on Linux and mac platform development.

**Comment by michelleannesimon** [comment]
I am closing this issue for the presenr.
