### ISSUE TITLE
Different set of links in profile between this and the Delphi version

### ISSUE THREAD

**Issue by fdumont7** [USEPA/SWMM-EPANET_User_Interface#411]
When I'm making a profile plot and I use the same nodes on the same project this version sometimes gives a different set of links in profile then the Delphi version which then gives different results on the plot.
Example:
Delphi:
![image](https://user-images.githubusercontent.com/47785290/77437637-47415f80-6dbb-11ea-8022-825363037651.png)

This version:
![image](https://user-images.githubusercontent.com/47785290/77437686-532d2180-6dbb-11ea-9082-089473ec5e80.png)

**Comment by PaulDudaRESPEC** [comment]
I found and fixed the error -- a logic error when specifying the nodes from downstream to upstream.  Here's what it looks like with the fix: 
![image](https://user-images.githubusercontent.com/13470278/81759842-cd148980-9493-11ea-87ac-3dd3d3da4a21.png)
