### ISSUE TITLE
SWMM project-specific .ini files not being created

### ISSUE THREAD

**Issue by barrc** [USEPA/SWMM-EPANET_User_Interface#412]
While researching #404 I found that project-specific .ini files are no longer being created in the same folder as the .inp file.  This seems to be happening for both MTP6r2 and from dev-ui-py3qt5.  I know the .ini files used to be created in the same folder.

If someone else could confirm this behavior is the same for them, along with the version they're running, that would be helpful.  

From a development environment at dev-ui-py3qt5 it looks like the data is being saved in one file shared for all projects.  For me the file is located at C:/Users/cbarr02/AppData/Roaming/Python/profiles/default/EPA/swmm.ini

**Comment by PaulDudaRESPEC** [comment]
I just made a commit that I think is a better way to handle the ini file issue -- @barrc maybe you can try it and see if this meets your needs.

**Comment by michelleannesimon** [comment]
This appears to be working properly in MTP7r0.  I will close this issue.
