### ISSUE TITLE
What is the python entry point?

### ISSUE THREAD

**Issue by R1EHB** [USEPA/SWMM-EPANET_User_Interface#413]
Working on compiling/running this on Linux. Was successful compiling base SWMM.

Not at all clear what and where the "main" module is. 

Can this be added to the documentation?

**Comment by michelleannesimon** [comment]
Hello,
We had thought that the GUI was developed for Windows - I have not tried it on Linux.  Where are the instructions that you are following?

**Comment by R1EHB** [comment]
Hi Michelle.  The GUI tools being used, Qt/Python/QGIS are cross platform. So compiling and running on Linux is quite possible; in fact, putting in the effort to do that can help figure out issues by differential analysis.

Regarding instructions, that's kind of the issue. The code tree doesn't seem to follow the typical standards for layout, and I haven't been able to put my eyes on the key instructions for figuring out how to get started. The instructions in base SWMM were very useful, and I was able to compile and run it on Linux with only a minor tweak to the top Cmake file.

Thanks, Erik

**Comment by michelleannesimon** [comment]
I am impressed that you were able to get it to run.  There are several sets of instruction.  I struggled through https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Getting-Started-as-a-Developer-in-Python-3 and then https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/Create-Installation-Package-for-Windows-10-(python-3-Qt-5-version).  Both of these have problems and need to be corrected.

Please send to me the location of the instructions that you are following.

**Comment by R1EHB** [comment]
Thanks Michelle.  Note that I created a fork of the main SWMM repo. See:

https://github.com/R1EHB/Stormwater-Management-Model
and in particular this branch:

https://github.com/R1EHB/Stormwater-Management-Model/tree/r1ehb_Develop

I will work through the links you provided above and report back.

Regards,  Erik

**Comment by dleutnant** [comment]
@R1EHB This has been on my swmm wish list for so long! I would love to get the GUI running on MacOS. Do you have some compile instructions already available?

**Comment by R1EHB** [comment]
Not yet; I have just started working on this myself.

As I figure things out, I will post updates.

Thanks!

Erik

**Comment by dleutnant** [comment]
Awesome! Feel free to contact me If you need some different environments to test with.

**Comment by R1EHB** [comment]
Thanks!

**Comment by michelleannesimon** [comment]
Is it frmMainSWMM.py?

**Comment by R1EHB** [comment]
Hi Michelle:

Yes, it is frmMainSWMM.py, in the directory SWMM-EPANET_User_Interface-master/src/ui/SWMM
