### ISSUE TITLE
Dependancies under Linux

### ISSUE THREAD

**Issue by schoeller** [USEPA/SWMM-EPANET_User_Interface#415]
Dear all,

thanks for the work done. 

I am trying to compile a fresh git clone on Ubuntu Focal and running into some dependency issues. 

```
Traceback (most recent call last):
  File "/home/sebastian/Downloads/SWMM-EPANET_User_Interface/src/ui/SWMM/frmMainSWMM.py", line 56, in <module>
    from ui.SWMM.frmTimeSeriesPlot import frmTimeSeriesPlot
  File "/home/sebastian/Downloads/SWMM-EPANET_User_Interface/src/ui/SWMM/frmTimeSeriesPlot.py", line 10, in <module>
    from ui.SWMM.frmTimeSeriesSelection import frmTimeSeriesSelection
  File "/home/sebastian/Downloads/SWMM-EPANET_User_Interface/src/ui/SWMM/frmTimeSeriesSelection.py", line 6, in <module>
    import Externals.swmm.outputapi.SMOutputSWIG as SMO
  File "/home/sebastian/Downloads/SWMM-EPANET_User_Interface/src/Externals/swmm/outputapi/SMOutputSWIG.py", line 7, in <module>
    from swmm.output import output as _lib
ModuleNotFoundError: No module named 'swmm'
```
I guessed that the missing module originates from https://github.com/OpenWaterAnalytics/swmm-python or https://github.com/SWMM-Project/swmm-python. Please confirm whether this is correct and if so how to compile that.

Kind regards

Sebastian

**Comment by PaulDudaRESPEC** [comment]
Hi Sebastian,

I think you can find the answer to your question in the wiki page here:
https://github.com/USEPA/SWMM-EPANET_User_Interface/wiki/2-Getting-Started-as-a-Developer-in-Python-3

In the section entitled “Install SWIG SWMM Output API from wheel”, there’s a link to satisfy that dependency.

It’s great to see folks bringing taking this effort to other platforms.  Good luck!

Paul D.

**Comment by schoeller** [comment]
@PaulDudaRESPEC 
Thanks for your reply. I am sharing my intermediate result. 

After installing cmake 3.17 as recommended in https://apt.kitware.com/ I was able to compile from source in the following order
1#https://scikit-build.readthedocs.io/en/latest/installation.html#install-from-source
2#https://github.com/SWMM-Project/swmm-python/releases/download/v0.6.0-rc.1/swmm-toolkit-0.5.0.tar.gz
When calling from python console manually I still run into this error:
```
>>> from swmm.toolkit import solver
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/swmm_toolkit-0.5.0-py3.8-linux-x86_64.egg/swmm/toolkit/solver.py", line 13, in <module>
    from . import _solver
ImportError: libswmm5.so: cannot open shared object file: No such file or directory
```
I have continued my quest here https://github.com/SWMM-Project/swmm-python/issues/2#issue-624476820

Kind regards

Sebastian

**Comment by schoeller** [comment]
@PaulDudaRESPEC 
Just to let you know, I was able to install dependencies on Linux, but in the end crashed into https://github.com/SWMM-Project/swmm-python/issues/2#issuecomment-634482008 
> The UI code needs to be refactored to use the updated swmm-toolkit package
