### ISSUE TITLE
EPANET_EDIT_MISSING_FEATURES

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#49]
Four items are not highlighted, inaccessible.  These are SELECT REGION, SELECT ALL, 			EDIT OBJECT and DELETE OBJECT

Undo - feature does not seem to work.

Redo - feature does not seem to work.

**Comment by TongZhai** [comment]
@rjanke20 Select region, select all, edit object, delete object menu items are not implemented yet.

**Comment by PaulDudaRESPEC** [comment]
Edit object and delete object actually are implemented -- they function only after a feature is selected.

**Comment by TongZhai** [comment]
These editing options were implemented since MTP4
