### ISSUE TITLE
Improvements to SWMM Output API - Large File Support

### ISSUE THREAD

**Issue by bemcdonnell** [USEPA/SWMM-EPANET_User_Interface#5]
In follow up to Colleen Barr's OutputAPI contribution for SWMM, I was hitting the file limits with output files greater than ~3gb.  I adjusted the offset data types and have posted the modified code in my repo.  These changes should let you get past the the ~3gb int offset limit.

bemcdonnell/SWMMOutputAPI/LargeFS-32

**Comment by MarkGrayRESPEC** [comment]
Thanks for speaking up about this. It is good to see another version of the SWMM Output API python wrappers, we will want to take a closer look and cross-pollinate with ours.

For those following along, the output API he is talking about is at:
https://github.com/bemcdonnell/SWMMOutputAPI/tree/LargeFS-32

The version in this project is at:
https://github.com/USEPA/SWMM-EPANET_User_Interface/tree/master/src/Externals/swmm/outputapi

**Comment by michaeltryby** [comment]
Thanks @bemcdonnell for pointing this out.

**Comment by MarkGrayRESPEC** [comment]
Is this change only needed when compiling for 32-bit? It looks like your 64-bit branch does not have this change.

**Comment by bemcdonnell** [comment]
@MarkGrayRESPEC, I believe you would need to change your offset data type for both 32 and 64-bit compilers. I believe @michaeltryby wants to use long int? That said, depending on what compiler you are using, compiling in 32 bit may require a different function from the standard fseek.  :)

Sorry for the confusion - I suggest referencing the LargeFS-32 branch.  I am going to merge the LargeFS-32 C code into the devx86-64 branch ASAP and do testing.

**Comment by michaeltryby** [comment]
@MarkGrayRESPEC While refactoring the EPANET Output API I learned that the file offset needs to be a 64 bit integer type on 64 bit systems.
