### ISSUE TITLE
EPANET_PROJECT_MENU

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#51]
Summary – only provides box for title…DELPHI EPANET provided summary of model	attributes.
Details – Nothing happens
Simulation options – Nothing happens

**Comment by PaulDudaRESPEC** [comment]
Summary -- agreed, more could be done with this feature
Details -- removed it in EPANET (only used in SWMM)
Simulation options -- connected it to Hydraulics options as in EPANET 2.0

**Comment by TongZhai** [comment]
Summary has already been updated to display title, notes, and general summary of model objects
