### ISSUE TITLE
EPANET_HELP

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#55]
ABOUT Box - Nice to have version identified, e.g., MTP3r3.  Also include python version.
HELP TOPICS - Not clear this works.

**Comment by PaulDudaRESPEC** [comment]
I added the version, as MTP4r1Dev for now, and I suggest we change that to MTP4r1 when we make the package.  

As for the Help topics, that works here in the development environment -- we should check that it works in the package when we build it.

**Comment by TongZhai** [comment]
In the MTP4 version, help topics are functioning.

**Comment by rjanke20** [comment]
Help is not working.  Opens Help dialogue panel but contains no help content.

**Comment by barrc** [comment]
#133 is another issue about EPANET help.  

I am able to see EPANET help content on my work machine (Windows 10 Enterprise), so maybe this is OS specific?

![image](https://user-images.githubusercontent.com/13906772/35586674-563294d4-05b0-11e8-99f2-dc5e62f99827.png)

**Comment by PaulDudaRESPEC** [comment]
I tested Help on another Windows 10 computer and found an issue with relative path names within the help file.  The revised compiled Help file will be included in future packages and will resolve this issue.
