### ISSUE TITLE
EPANET_FILE_IMPORT_GIS_MAP

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#56]
File Menu - Import - Map - Dialogue box comes up and asks me if I want to replace the pipes in my uploaded inp file with the "roads" shape file that I am trying to import.  I believe we want to be able to have the network model projected and aligned with the IMPORTED roads layer.

**Comment by TongZhai** [comment]
The File -> Import -> Map is reprogrammed to perform the same function as the plug in import from GIS to create model
