### ISSUE TITLE
Is this project on hiatus?

### ISSUE THREAD

**Issue by dickinsonre** [USEPA/SWMM-EPANET_User_Interface#57]
I have been wondering about the lack of activity here for months but wanted to post a query about it.  Is the project on hiatus or on hold for the 1st months of 2017 - I have used the SWMM5 GUI and it looks good.

**Comment by TongZhai** [comment]
Currently, active development is on the dev-ui branch. We will update the master branch at the conclusion of MTP4, which is scheduled in the near future.

**Comment by dickinsonre** [comment]
Thanks, I see your recent additions, now.  My apologies.
