### ISSUE TITLE
Stop run button does not stop the run

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#6]
While a model is run, pushing the "Stop" button does not stop the run and the results can be retrieved.

![stop-run](https://cloud.githubusercontent.com/assets/1942312/16146556/51b9c13a-3487-11e6-96d4-942a3f10ae06.png)

**Comment by MarkGrayRESPEC** [comment]
The Stop button now functions correctly during an EPANET run in the dev-ui branch.
