### ISSUE TITLE
EPANET MTP4 doesn't run on fresh Windows 7

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#62]
After installation on a 64bits Windows 7 machine the program doesn't run. The cmd window appears for a split second and that is it. On a Windows 8.1 machine, where MTP3 was installed previously, MTP4 runs.

**Comment by TongZhai** [comment]
We just start to realize the issue with Windows 7 and PyQt program. The program is developed on Windows 7 and Windows 10 and tested on clean Windows 8.1 and Windows 10. We will continue to search for solution to the windows 7 deployment problem. By the way, it is 'MTP' as in Minimum Testable Product.

**Comment by eladsal** [comment]
Any tests on Windows Server machines?

**Comment by TongZhai** [comment]
No

**Comment by eladsal** [comment]
Tested on Windows Server 2012 R2, same problem as with Windows 7.

**Comment by accumodel** [comment]
I can't get SWMM or NET version to run on fresh Windows 10 64 bit machine

**Comment by accumodel** [comment]
My previous comment was for MTP4.  I also tried installing MTP3r3 and it worked as expected.  Then I ran the MTP4 installer again and still just the cmd window shows up briefly with no interface launch.

**Comment by TongZhai** [comment]
The installation packages are updated to handle Win7, Win 8, and Win 10. Please uninstall your current software and re-download the updated installer to try again, please reply back if it worked so we can close this issue, thanks.

**Comment by eladsal** [comment]
Where are the new installation files located? is there a revision for MTP4?

**Comment by TongZhai** [comment]
We just did an in-situ update per installation issue, so still MTP4 release. Just re-download the two zip file installers and give them a try

**Comment by accumodel** [comment]
I have two machines on which I am trying to run the newest iteration of MTP4 that Tong mentioned today.  They are both fresh installs of Windows 10 64 bit.  I was able to get the GUI to launch on one machine but not on the other.

**Comment by TongZhai** [comment]
@accumodel hmm, I wonder how the two window 10 boxes differs... some description of their environments (has QGis installed or not etc) and exact windows version (home, enterprise, prof etc) would be good
@eladsal have you been able to run on your win7 and window server 2012 R2?

**Comment by eladsal** [comment]
Sorry for the delay, these machines are at a different location.

Unfortunately, I'm facing the same issue with the new installation files.
The Windows 7 is the Enterprise version SP1 (no QGIS or Python). The Windows 2012 R2 is the Standard edition on a VM. No QGIS but Python and Qt are installed.

**Comment by TongZhai** [comment]
@eladsal on both systems, please try run the programs from command-line in a DOS cmd window by typing the exe name, i.e. EPANET-UI.exe and copy the print out message and send to us

**Comment by eladsal** [comment]
Printouts attached. I see some "c:\users\tong~1.zha"paths there, that might be wrong.
[win7.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/989761/win7.txt)
[win2012.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/989763/win2012.txt)

**Comment by accumodel** [comment]
I just installed QGIS on the second machine and now both machines will launch EPANET GUI.  Thanks for the help.  Will it be a requirement in the future to first install QGIS?  Or is this just a temporary issue?

**Comment by accumodel** [comment]
Here is my successful launch log in case it is helpful.

[Win10 EPANET log.txt](https://github.com/USEPA/SWMM-EPANET_User_Interface/files/990132/Win10.EPANET.log.txt)

**Comment by TongZhai** [comment]
@accumodel thanks, your message log is the same as the message log from our internal test on win10
@eladsal thanks for the message log, we will trace the problem. I believe that path is an internal log of the directory when the the package is being built, it is not assuming users would have those directories...

**Comment by TongZhai** [comment]
@accmodel so, you just installed full QGIS software, then the software is running, this sounds like the behavior of the previous installer, we just updated the installers (May 9th around 3PM) for MTP4 as zip files, did you try the new installers?

**Comment by accumodel** [comment]
@TongZhai Yes, that is correct.  I may have the earlier installer.  The time stamp on it is 5/9/2017 2:42pm
