### ISSUE TITLE
EPANET - first added junction is not plotted in the click coordinates

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#63]
After starting the program, selecting the 'Add junction' toolbar option and clicking the map area, the first junction is not plotted in the clicked coordinates (it is plotted in the center of the screen). The next junctions are plotted correctly.

**Comment by TongZhai** [comment]
This behavior is by design. It is actually drawn on the clicked coordinates, just that the map canvas needs to "zoom to" the first element drawn. If you move cursor to the point on the center of the screen, it is still the same coordinates.

**Comment by eladsal** [comment]
I think this design is not what the user expects. A junction should appear where the user clicks on the map.
