### ISSUE TITLE
EPANET - new elements not displayed until zoom full extent for new network

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#64]
Start the program
Add a few junctions
Select 'New' from the 'File' menu
Click 'Yes' for 'Discard current project?'
Add new junction and other elements - they are not displayed automatically until zoom full extent

**Comment by TongZhai** [comment]
Click the "zoom full extent" button to see the new elements.

**Comment by eladsal** [comment]
User shouldn't need to click the zoom button. New network should behave the same way as when the program starts.

**Comment by TongZhai** [comment]
I modified the issue description as they are plotted, just needing a refresh.
