### ISSUE TITLE
EPANET - Trace and AGE results are shown in wrong units

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#65]
When running TRACE\AGE analysis, results in graphs and tables are shown in mg/L instead of percents\hours.

**Comment by TongZhai** [comment]
I ran Net1 example with tracing on node 12 and the resulting graph and table are shown in mg/L. This was done using the **official EPANET program (not our program)**. So, could you elaborate on what exactly your steps were to arrive at those percents\hours graphs?

**Comment by eladsal** [comment]
Just regular trace and age simulations and looking at the tables and graphes:
![screenshot 317](https://cloud.githubusercontent.com/assets/1942312/26436097/b5d31c96-411c-11e7-852e-4e65ab4c5295.png)

![screenshot 318](https://cloud.githubusercontent.com/assets/1942312/26436106/d081150c-411c-11e7-91d6-1c1a4780fe31.png)

![screenshot 319](https://cloud.githubusercontent.com/assets/1942312/26436120/ec97d0f0-411c-11e7-8c2b-4f795b85fb5e.png)
