### ISSUE TITLE
EPANET - selected node\link is not shown in graph\table forms

### ISSUE THREAD

**Issue by eladsal** [USEPA/SWMM-EPANET_User_Interface#66]
When selecting a node or a link on the map and opening the graph\table result form, the selected entity is not selected on the list. This makes it hard to select a specific element (especially on large networks).

**Comment by dickinsonre** [comment]
You can enter the name of the element in the box and a graph appears but there does seem to be a lot of steps in the generation of a graph.  The graphs do look good and correct.

**Comment by eladsal** [comment]
@dickinsonre you can do that also in EPANET but this is not very convenient, much easier to select it on the map. The ID can be up to 32 characters.

**Comment by TongZhai** [comment]
this issue is addressed with commit 0f5439ab6541af33b9cf7b009d65c93360b1c7c0
now graph objects can be selected from map for SWMM and EPANET. Also, for EPANET, selection on form will also trigger selection on map as visual cue
