### ISSUE TITLE
EPANET:  Vertex Editor - Not clear how it works.

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#72]
It is not clear to the user how after selection of the Vertex Editor from the tool bar it works.

**Comment by TongZhai** [comment]
Currently, the vertex editing tool is for editing SWMM subcatchment polygons, so the tooltip for that tool is updated. Essentially, after clicking on that button, the polygon's vertices will change into red cross, the following operations are allowed (these are all default behavior of the QGIS program):
- the user can drag any vertex to new location 
- a double-click on any line segment will add a new vertex
- a right-click on any vertex will delete it

clicking on the vertex editor tool icon will toggle between the editing and non-editing mode, and it will prompt the user whether to save the changes if changes were made.
