### ISSUE TITLE
EPANET: Very large model simulation Output Error #437

### ISSUE THREAD

**Issue by ArnieStrasser** [USEPA/SWMM-EPANET_User_Interface#75]
After running a model an error message says "EPAnet Output Error #437". The model run is successful and an output file is generated but the results are not displayed.

**Comment by TongZhai** [comment]
Please provide input file and any custom changes before running the model. Please ensure install the latest release ([MTP4r1](https://github.com/USEPA/SWMM-EPANET_User_Interface/releases/tag/MTP4r1)).

**Comment by ArnieStrasser** [comment]
I installed the latest release and reran the model and still get the same
error and no results.
 This is a very large model, 260,000 links.

I tried a smaller model and there wasn't an error. The only results I can
get is using the report menu and selecting table. There are no graphical
results like a legend that can be modified, or flow arrows or output
results as graphical attributes on the nodes or links. Is that still being
worked on or am I doing something wrong?

Thanks

Arnie

**Comment by TongZhai** [comment]
The result graphing and color-coding of output on the map are all functional, at least on the models we tested. The flow arrow feature will be a new feature to be developed. I am guessing that the software was able to handle the visual display and manipulation of your large model correctly, right? Then, this looks like a SWMM/EPANET model engine issue. If you are willing to provide us with your model input file, we can definitely try to debug this from model engine side as we have not run a model as large as yours for sure.

**Comment by ArnieStrasser** [comment]
Yes, the color coding and graphing worked on the small model but not the large since there was no output file. Flyover map labeling as well as graphical attribute results don’t work even on the small model. When will these critical features be developed? If you need to look at tables for results or select individual features to graph them it won’t be very useful to users with large models. The Project Objects in the layers tab have predefined color ramps which don’t lend to user visual aid of the results. Will there be more flexibility in future developments such as a legend editor as indicated in the help file?  If so when? Direction of flow is also critical for viewing the results and will be problematic if that isn’t a near term development feature.

 

I don’t have authorization to release the model for your review but will see if the owner is willing to if you agree to a nondisclosure agreement.

**Comment by TongZhai** [comment]
The features you mentioned (including flow direction and symbol editor etc) are all good features to have, we are always looking for partners in developing new features such as these. We are very interested in having a joint discussion with you (and your client) to potentially collaborate on these development efforts. We can communicate individually if you are interested. We will certainly honor the nondisclosure agreement on any data you share with us as the data will be used for software development purpose only.

**Comment by ucchejbb** [comment]
I'm getting the same error (#437) for a system that has ~16,000 nodes and ~18,000 links. I ran this on the newest release client EPANET-UI-MTP4r1. Unfortunately, I can't share this network for testing at this time either. This network isn't as large, but still encountering the same error.

**Comment by TongZhai** [comment]
We have identified the source of the #437 error message and a fix will be posted.

**Comment by michaeltryby** [comment]
Error 437 has nothing to do with large files. It is caused when the Output API validates a binary file saved during a simulation with warnings. It should be handled as a warning instead of an error. While I was fixing this I encountered another bug with the Output API and fixed it as well. All good, except the API has changed as a result. 

@TongZhai since I shared this code with you last year I have added the Output API to the SWMM and EPANET repositories. I would like to standardize on those versions and get away from having a forked version located in this project. Make sense?

**Comment by michaeltryby** [comment]
Oops.

**Comment by michaeltryby** [comment]
@TongZhai What I propose we do is this. I will fix the Error 437 bug by converting it to Warning 10 to get this issue resolved in the most straight forward way possible. I will update the versions of the Output API that I am maintaining with bug fixes and API changes. I will create a separate issue for converting over and standardizing on those versions. Sound good?

**Comment by TongZhai** [comment]
@michaeltryby Ok, will wait for your updates.

**Comment by TongZhai** [comment]
@michaeltryby Are you also working on resolving the 64bit simulation convergence issue? When I ran Rob’s large model with the 64bit EPANET engine, it was really slow after 50% progress, seems to be related to the speed of convergence.

**Comment by michaeltryby** [comment]
@TongZhai Yes I am working on the 64 bit issue as well.

**Comment by TongZhai** [comment]
The error #437 problem is fixed by updating the EPANET output access api, which is implemented via [issue #77](https://github.com/USEPA/SWMM-EPANET_User_Interface/pull/77); That bug prevented the generation of output file, hence the subsequent inaccessible output problems, which are all related to this issue.
