### ISSUE TITLE
Pumps are obscured if links are colored

### ISSUE THREAD

**Issue by ucchejbb** [USEPA/SWMM-EPANET_User_Interface#76]
When plotting results for links, the pump icons are obscured by the new line color. This makes it difficult to identify which links are pumps when viewing graphical results.

**Comment by TongZhai** [comment]
@ucchejbb this is fixed ([b5386ba0e48992eee409c9a4240a2799a6c113ef](https://github.com/USEPA/SWMM-EPANET_User_Interface/commit/b5386ba0e48992eee409c9a4240a2799a6c113ef)); now when the GIS map is updated to display certain pipe output attribute, all special symbols of model objects are retained.
