### ISSUE TITLE
EPANET engine convergence and results affected by port to 64 bit

### ISSUE THREAD

**Issue by michaeltryby** [USEPA/SWMM-EPANET_User_Interface#78]
Testing has revealed that convergence characteristics and results are being affected by port of numerical engine to 64 bit.

**Comment by TongZhai** [comment]
Yeah, I am not surprised, we experienced the same kind of issue when we tried to run 64bit HSPF

**Comment by michaeltryby** [comment]
@TongZhai how did you guys get is resolved? I was thinking of using a static analyzer to identify the problematic parts of the code.

**Comment by TongZhai** [comment]
@michaeltryby We are still using the 32bit HSPF...
