### ISSUE TITLE
EPANET-Report-Graph-SystemFlowBalance missing units on y axis

### ISSUE THREAD

**Issue by jlkittle** [USEPA/SWMM-EPANET_User_Interface#8]
No units on y axis (Flow) in EPANET-Report-Graph-SystemFlowBalance

**Comment by eladsal** [comment]
The units from the INP are not shown correctly across the UI (in "status-bar", in graphs and tables). Its always CFS. See an example in the network I loaded for issue #7.

**Comment by MarkGrayRESPEC** [comment]
Display and selection of units are not yet completely implemented in the interface as of MTP 2.

**Comment by MarkGrayRESPEC** [comment]
Display of units (as read from the EPANET output) is now implemented (in the dev-ui branch) for EPANET and SWMM graphs and tables produced from the model output. Selection of units while editing the input file is outside the scope of this issue and is not yet implemented.
