### ISSUE TITLE
EPANET_UI_Slow_&_Nonresponsive_Graphing

### ISSUE THREAD

**Issue by rjanke20** [USEPA/SWMM-EPANET_User_Interface#81]
After a model simulation is performed, the graph results process seems slow and unresponsive at times.  Larger models seem more problematic.  The problem seems to be especially acute when the user clicks on various nodes and/or graph type within the user interface.  Models of varying complexity (e.g., 2,000 to 55,000 nodes) load easily and run as expected.

**Comment by TongZhai** [comment]
This is due to the event loop related to selecting features on map while selecting objects for graphing, [a fix](https://github.com/USEPA/SWMM-EPANET_User_Interface/commit/cda0b9f1889) that skips that event loop is done, now it is very responsive and fast even in very large models.
