### ISSUE TITLE
UI Issue with EPANET 2.1 DLL

### ISSUE THREAD

**Issue by ucchejbb** [USEPA/SWMM-EPANET_User_Interface#82]
I replaced the current EPANET dll with the one for EPANET 2.1 to see if that would work with the new UI (MTP4.1). The UI will run some models (Net1 for example), but not Net3 Net7. I'm getting 400 series errors which are new to EPANET2.1, related to the binary reader. I'm getting specifically 434, 435,  and 437.  It seemed like the UI was running the models, but wouldn't 100% complete the simulations.

**Comment by eladsal** [comment]
Jonathan, the new EPANET 2.1 doesn't raise errors 434, 435 and 437. The only 400 series error in 2.1 is 401. All errors are list [here](https://github.com/OpenWaterAnalytics/EPANET/blob/master/src/text.h).

**Comment by ucchejbb** [comment]
Elad, Thanks for the response. I'm just reporting what I'm seeing. The outputapi.c code on OpenWaterAnalytics is configured to throw a variety of 400 series errors. I will acknowledge that I'm not sure how 437 was generated, since when I searched that number it didn't show up as being in the code.

**Comment by samhatchett** [comment]
a 437 is generated here:
https://github.com/USEPA/SWMM-EPANET_User_Interface/blob/master/src/Externals/epanet/outputapi/outputapi.c#L801

... likely the UI is calling the outputApi library.

**Comment by ucchejbb** [comment]
Thanks Sam, I was looking at the EPANET2.1 source code, not the UI, which was why I was missing that error code. I was assuming those errors were coming from the updated dll, not the UI.

**Comment by samhatchett** [comment]
my best guess is that the UI-versioned outputApi library doesn't like something in the engine-2.1-generated binary file?

**Comment by ucchejbb** [comment]
Makes sense to me. I'll look at the inp files to see what features might be different (WQ vs just hydraulics).

**Comment by TongZhai** [comment]
@michaeltryby has recently [updated both the EPANET engine and output API to deal with hydraulic warning messages](https://github.com/USEPA/SWMM-EPANET_User_Interface/issues/75), this will be in the next release which we are about to push out very soon. Please take a look at that thread to see if that's relevant to this issue. Also, where could we get your engine 2.1 DLL for testing with the new UI?

**Comment by samhatchett** [comment]
https://github.com/OpenWaterAnalytics/EPANET/releases/tag/v2.1

**Comment by TongZhai** [comment]
Ok, got the win DLL, and my initial trial run using this 2.1 DLL seems to be working on a 12000+ nodes network and a 55000+ nodes network. So, we will test this DLL further before next release. Send us the input files for debugging should you desire.

**Comment by ucchejbb** [comment]
@TongZhai I know the Net3 examples that was included in the MTP4.1 produced an error on my end. I tried a few other examples that I had from previous example sets, and I think Net6 didn't run either. I'll look through the inp files to see if I can figure out what might be causing problems.

**Comment by TongZhai** [comment]
@ucchejbb I think we have fixed some minor bugs in some core libraries after the MTP4.1 release. Those bug fixes might be the reason that I can run Net3 example without error. I have not seen the 'Net6' example, In the official EPANET distro, there are only 3 examples as in the Inptools package...

**Comment by woohn** [comment]
@TongZhai I want to describe the bugs related with Net3 in detail in addition to @ucchejbb comments. 
1) Pump STATUS
- EPANET2: pump 10 is closed and pump 335 is open at initial status.   
- MTPr4: When I open the Net3.inp from the new UI, it showed both pumps are closed. However, when I click to run, it simulates as like both pumps are open. 
2) Missing coordinate for node 177
- EPANET2: when importing INP file, it indicates the user for missing coordinate.
- MTPr4: does not have a warning message.

**Comment by TongZhai** [comment]
@woohn, yes, those are among the bugs that have been fixed since the MTP4r1 release.

**Comment by woohn** [comment]
@TongZhai That's good to know they are already fixed. Thanks.

**Comment by TongZhai** [comment]
Here I will reference the relevant code enhancements and bug fixes per this thread and close this issue:
- ensure only coordinates validity for display and in input file, [3b5acb980d4dd0b647d1779de441c34788831991](https://github.com/USEPA/SWMM-EPANET_User_Interface/commit/3b5acb980d4dd0b647d1779de441c34788831991)
- Save the full map extent for SWMM model, [0f76311e0da952757ce09d7cb74f6fcca95f7295](https://github.com/USEPA/SWMM-EPANET_User_Interface/commit/0f76311e0da952757ce09d7cb74f6fcca95f7295)
