### ISSUE TITLE
Element editor window feature requests

### ISSUE THREAD

**Issue by rickscr** [USEPA/SWMM-EPANET_User_Interface#87]
Usability problems with the element editor windows (tank editor, pipe editor, junction editor, etc):
1. The default window size is not large enough to display all the fields. The user must resize the window or scroll every time if they want to see all the fields. Part of the problem is that there is a lot of wasted vertical space between fields. 
2. Multiple editor windows for the same element can be opened simultaneously. The user should only be able to open one window for each element at a time to avoid confusion. 
3. The data field widths cannot be resized. This can cause problems if the data cannot fit in the default width. For example, long names, description, and patterns will be cut off. 

![image](https://user-images.githubusercontent.com/23215317/30229342-b80d73aa-949e-11e7-89e0-e34371acc4cc.png)

To solve these problems, consider making the editor window permanently dockable, similar to the InfoWater Model Explorer or WaterCAD Properties windows. The InfoWater/WaterCAD windows will display all the properties for whatever single element is selected, of any type. See the examples below.

Innovyze InfoWater
![image](https://user-images.githubusercontent.com/23215317/30229893-028a75ca-94a1-11e7-8571-e97ed8dc6c88.png)

Bentley WaterCAD
![image](https://user-images.githubusercontent.com/23215317/30229725-4eede04c-94a0-11e7-9009-348215a2b682.png)

**Comment by PaulDudaRESPEC** [comment]
Added enhancements to allow column resizing, make dialog modal, and reduce white space between fields.
