### ISSUE TITLE
[question] epanet changes and regression testing

### ISSUE THREAD

**Issue by samhatchett** [USEPA/SWMM-EPANET_User_Interface#9]
I noticed the regression tests in `src/Externals` and had a question about the scope of this development project. Is this project likely to change the epanet internals and maintain its own version of that toolkit? And is that why there are these regression tests here? 

If that is not the case, then using [Git Submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) to link to the OWA repository would be a great way to simplify the epanet and epanet-testing code, given that OWA has most of this already and is continuing to improve it. Also, since there aren't really any ideological fights going on here, this kind of bifurcation seems premature ;)

**Comment by michaeltryby** [comment]
@samhatchett  I was in Atlanta last week with the Aqua Terra team working on the project. Mark and I developed the regression test with the idea that we would cross pollinate with OWA and EPA repositories. Feel free to make use of it as you see fit. 

I agree I don't think EPANET regression testing necessarily belongs here. I would like to get the src/Externals folder cleaned up some. Git Submodules sounds like a good idea.
